esphome:
  name: apitest
  friendly_name: APItest

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TTnz82t3lKyFJXjxYDR2bZdGXFayj2dg/MVSaBjj4S0="

ota:
  platform: esphome
  password: "a07b49fee8551b449ee80625f621e024"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Apitest Fallback Hotspot"
    password: "201jzEWyuOoP"

web_server:
  port: 80


captive_portal:
    