esphome:
  name: bin-can-test1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TTnz82t3lKyFJXjxYDR2bZdGXFayj2dg/MVSaBjj4S0="

ota:
  platform: esphome
  password: "88e924d8ee6f46a7d85029274e1d162d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bin-Can-Test1 Fallback Hotspot"
    password: "jdNPhTl36Euq"

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  
sensor:  
  - platform: aht10
    temperature:
      name: "Sewing Room AHT10 Temperature"
    humidity:
      name: "Sewing Room AHT10 Humidity"
    update_interval: 60s

web_server:
  port: 80


captive_portal: