esphome:
  name: c3holdbuild0
  friendly_name: c3holdbuild0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3kgRq4LQUS9wXWnbJLMKaqZp8jA4YGvs0Z0qqh/8TD0="

ota:
  - platform: esphome
    password: "996b6724b08487d633d0931baf417747"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "C3Holdbuild0 Fallback Hotspot"
    password: "9Nf76oKPYVY9"

web_server:
  port: 80

captive_portal:
    