esphome:
  name: devtest2
  friendly_name: DevTest2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "niiewGACG5gyL/0W0lfDs/vAnsquKtQ0tPykfgUkTFw="

ota:
  platform: esphome
  password: "8a147e08981cb0d93a8202cf535424b2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Devtest2 Fallback Hotspot"
    password: "wiWqmpjgC89b"


esp32_ble_tracker:


i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  
sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature devtest2"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure devtest2"
    humidity:
      name: "BME280 Humidity devtest2"
    address: 0x76
    update_interval: 60s
  
  - platform: wifi_signal
    name: 
      devtest2 WiFi Signal Sensor"
    update_interval: 60s

  - platform: inkbird_ibsth1_mini
    mac_address: 49:24:03:04:0D:43
    temperature:
      name: "Inkbird IBS-TH1 Temperature"
    external_temperature:
      name: "Inkbird IBS-TH1 External Temperature"
    humidity:
      name: "Inkbird IBS-TH1 Humidity"
    battery_level:
      name: "Inkbird IBS-TH1 Battery Level"


web_server:
  port: 80


captive_portal:
    