substitutions:

  device_name: "diymalltft1"
  friendly_name: "diymalltft1"
  board_type: esp32dev
  framework: esp-idf # arduino or esp-idf (recommended for ESP32)

### END ###

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: ${board_type}
  framework:
    type: ${framework}


#from https://community.home-assistant.io/t/esp32-2432s028r-sunton-2-8-cyd-config/780600

# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: "T8ntv25OZwYgC2fKPABSQBzWwlWDeuOrmpRbNLP0TME="

ota:
  - platform: esphome
    password: "c64bbd9a3791f71c7645c1610f5dc589"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - component.update: my_online_image
    - lvgl.label.update:
        id: lbl_id
        text: 
          format: "%.0fdBm"
          args: [ 'id(wifi_sig).get_state()' ]
            

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Diymalltft1 Fallback Hotspot"
    password: "CBin8qPP3SLJ"


packages:
  common_files:
    url: https://github.com/agillis/esphome-configs
    ref: main # optional
    files: [modules/common/color.yaml,
            modules/common/fonts.yaml]


i2c:
  - sda: 27
    scl: 22
    scan: true

spi:
  - id: tft
    clk_pin: 14
    mosi_pin: 13
    miso_pin:
      number: 12
      ignore_strapping_warning: true
  - id: touch
    clk_pin: 25
    mosi_pin: 32
    miso_pin: 39

output:
  - id: backlight_pwm
    platform: ledc
    pin: 21
  - id: output_red
    platform: ledc
    pin: 4
    inverted: true
  - id: output_green
    platform: ledc
    pin: 16
    inverted: true
  - id: output_blue
    platform: ledc
    pin: 17
    inverted: True
      


light:
  - id: back_light
    platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    restore_mode: ALWAYS_ON
  - id: led
    platform: rgb
    name: RGB LED
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago
    on_time_sync:
#      - script.execute: time_update
      - if:
          condition:
            lambda: 'return id(device_last_restart).state == "";'
          then:
            - text_sensor.template.publish:
                id: device_last_restart
                state: !lambda 'return id(homeassistant_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
    on_time:
      - minutes: "*"
        then:
          - script.execute: wifisig_update

script:
  - id: wifisig_update
    then:
      - lvgl.label.update:
          id: lbl_id
          text:
            format: "%.0fdBm"
            args: [ 'id(wifi_sig).get_state()' ]

display:
  - id: main_display
    platform: ili9xxx
    model: ILI9341
    spi_id: tft
    rotation: 270
    cs_pin:
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number:  2
      ignore_strapping_warning: true
    invert_colors: false
    update_interval: never
    auto_clear_enabled: false
    show_test_card: True

touchscreen:
  - id: main_touchscreen
    platform: xpt2046
    spi_id: touch
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
    transform:
      mirror_x: true
      mirror_y: true
      swap_xy: true
    # on_touch:
    #   - lambda: |-
    #         ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
    #           touch.x,
    #           touch.y,
    #           touch.x_raw,
    #           touch.y_raw
    #         );


http_request:
  verify_ssl: False

online_image:
  #  - url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/280px-PNG_transparency_demonstration_1.png"
  #- url: "http://homeassistant.local:8123/local/test1.png"
#  - url: "http://homeassistant.local:8123/local/Paris800_480.png"
  - url: "http://homeassistant.local:8123/local/bulb.png"
    format: png
    id: my_online_image
    type: RGB565
#    resize: 100x100
    on_download_finished:
      #  component.update: my_display
      lvgl.image.update:
        id: first_image
        src: my_online_image

image:
  - file: dice.png
    id: Paris_image
    resize: 750x420
    type: RGB565

lvgl:
  buffer_size: 25%
  pages:
    - id: main_page
      bg_color: 0x022000
      widgets:
          - image:
              src: Paris_image
              align: CENTER 
              id: first_image
    
    - id: page_2
      widgets:
        - label:
            align: CENTER
            id: lbl_id
            text_font: montserrat_28
            recolor: true
            text: "#FF0000 write# #00FF00 colored# #0000FF text#"

        - label:
            align: TOP_MID
            id: lbl_symbol
            text_font: montserrat_28
            text: "\uF013"

    - id: page_3
      widgets:
        -  obj:
            x: 10
            y: 10
            width: 220
            height: 300
            bg_color: green
   
  
  top_layer:
    widgets:
      - buttonmatrix:
          align: bottom_mid
          styles: header_footer
          pad_all: 0
          outline_width: 0
          id: top_layer
          items:
            styles: header_footer
          rows:
            - buttons:
              - id: light_on
                text: "\uF0355"
                on_press:
                  then:
                    light.turn_on: back_light
              - id: page_prev
                text: "\uF053"
                on_press:
                  then:
                    lvgl.page.previous:
              - id: page_home
                text: "\uF015"
                on_press:
                  then:
                    lvgl.page.show: main_page
              - id: light_off
                text: "\uF0355"
                on_press:
                  then:
                    light.turn_off: back_light
              - id: page_next
                text: "\uF054"
                on_press:
                  then:
                    lvgl.page.next:            
  
  theme:
#    label:
#     text_font: roboto24 # set all your labels to use your custom defined font
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 1
      text_color: 0xFFFFFF
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked: # set some button colors to be different in checked state
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
    buttonmatrix:
      bg_opa: TRANSP
      border_color: 0x0077b3
      border_width: 0
      text_color: 0xFFFFFF
      pad_all: 0
      items: # set all your buttonmatrix buttons to use your custom defined styles and font
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
#        text_font: roboto24
        pressed:
          bg_color: 0x006699
          bg_grad_color: 0x00334d
        checked:
          bg_color: 0x1d5f96
          bg_grad_color: 0x03324A
          text_color: 0x005580
    switch:
      bg_color: 0xC0C0C0
      bg_grad_color: 0xb0b0b0
      bg_grad_dir: VER
      bg_opa: COVER
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_grad_color: 0xC0C0C0
        bg_grad_dir: VER
        bg_opa: COVER
    slider:
      border_width: 1
      border_opa: 15%
      bg_color: 0xcccaca
      bg_opa: 15%
      indicator:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
  style_definitions:
    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 100%
      height: 30


text_sensor:
  - platform: version
    id: esphome_version
    name: "ESPHome Version"
        
  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic

  - platform: homeassistant
    id: weatherforecastd1
    entity_id: sensor.weather_forecast_d1        

sensor:
  - platform: wifi_signal
    id: wifi_sig
    name: "DIYMall WiFi Signal Sensor"
    update_interval: 60s
  
  - platform: adc
    pin: 34
    name: "Ambient Light Level"
    update_interval: 60s

  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.first_air_quality_monitor_temperature

  - platform: homeassistant  
    id: inside_humidity
    entity_id: sensor.first_air_quality_monitor_humidity

  - platform: uptime
    type: seconds
    name: Uptime Sensor
 
# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"



web_server:
  port: 80
  include_internal: True
  version: 3

captive_portal:
