substitutions:

  device_name: "diymalltft1"
  friendly_name: "diymalltft1"
  board_type: esp32dev
  framework: esp-idf # arduino or esp-idf (recommended for ESP32)

### END ###

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: ${board_type}
  framework:
    type: ${framework}


#from https://community.home-assistant.io/t/esp32-2432s028r-sunton-2-8-cyd-config/780600

# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: "T8ntv25OZwYgC2fKPABSQBzWwlWDeuOrmpRbNLP0TME="

ota:
  - platform: esphome
    password: "c64bbd9a3791f71c7645c1610f5dc589"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Diymalltft1 Fallback Hotspot"
    password: "CBin8qPP3SLJ"


i2c:
  - sda: 27
    scl: 22
    scan: true

spi:
  - id: tft
    clk_pin: 14
    mosi_pin: 13
    miso_pin:
      number: 12
      ignore_strapping_warning: true
  - id: touch
    clk_pin: 25
    mosi_pin: 32
    miso_pin: 39

output:
  - id: backlight_pwm
    platform: ledc
    pin: 21
  - id: output_red
    platform: ledc
    pin: 4
    inverted: true
  - id: output_green
    platform: ledc
    pin: 16
    inverted: true
  - id: output_blue
    platform: ledc
    pin: 17
    inverted: True
      




light:
  - id: backlight
    platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    restore_mode: ALWAYS_ON
  - id: led
    platform: rgb
    name: RGB LED
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF


display:
  - id: main_display
    platform: ili9xxx
    model: ILI9341
    spi_id: tft
    cs_pin:
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number:  2
      ignore_strapping_warning: true
    invert_colors: false
    update_interval: never
    auto_clear_enabled: false
    show_test_card: True

touchscreen:
  - id: main_touchscreen
    platform: xpt2046
    spi_id: touch
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
    transform:
      mirror_x: true
    # on_touch:
    #   - lambda: |-
    #         ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
    #           touch.x,
    #           touch.y,
    #           touch.x_raw,
    #           touch.y_raw
    #         );

lvgl:
  buffer_size: 25%
  displays:
    - main_display
  touchscreens:
    - main_touchscreen
  pages:
    - id: main_page
      widgets:
        - label:
            align: CENTER
            text: 'Lance Rules! Yes he does...'
  




sensor:
  - platform: wifi_signal
    name: "DIYMall WiFi Signal Sensor"
    update_interval: 60s
  
  - platform: adc
    pin: 34
    name: "Ambient Light Level"
    update_interval: 60s

  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.first_air_quality_monitor_temperature

  - platform: homeassistant  
    id: inside_humidity
    entity_id: sensor.first_air_quality_monitor_humidity

  - platform: uptime
    type: seconds
    name: Uptime Sensor
 
# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"



web_server:
  port: 80
  include_internal: True
  version: 2

captive_portal:
