esphome:
  name: epaper1
  friendly_name: epaper1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "sptBK8w6ZAhtEPI/S5X7BuHFoLi7u6IqG6pJVPU9g3s="

ota:
  - platform: esphome
    password: "8b483b284d5c3ce12c98f7568297577b"

globals:
  - id: wifi_status
    type: int
    restore_value: no
    initial_value: "0"
  - id: recorded_display_refresh
    type: int
    restore_value: yes
    initial_value: '0'    


time:
  - platform: homeassistant
    id: homeassistant_time
          

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Epaper1 Fallback Hotspot"
    password: "3DNTqSHQmojf"

spi:
  clk_pin: GPIO8
  mosi_pin: GPIO10

# Font definitions
font:
  - file: "gfonts://Roboto"
    id: font_large
    size: 96
  - file: "gfonts://Roboto"
    id: font_medium
    size: 16
  - file: "gfonts://Roboto"
    id: font_small
    size: 12

display:
  - platform: waveshare_epaper
    id: main_display
    cs_pin: GPIO3
    dc_pin: GPIO5
    busy_pin: GPIO4
    reset_pin: GPIO2
    model: 7.50inv2
    update_interval: 600s
    rotation: 0
    lambda: |-
      // Default display content
      it.printf(10, 10, id(font_large), "Lance Rules!");



sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  - platform: uptime
    type: seconds
    name: Uptime Sensor
    


  - platform: uptime
    name: Uptime

  - platform: internal_temperature
    name: "Internal Temperature"

   


text_sensor:
  - platform: version
    id: esphome_version
    name: "ESPHome Version"

  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic

  - platform: template
      name: "Display Refresh Count"
      accuracy_decimals: 0
      unit_of_measurement: "Refreshes"
      state_class: "total_increasing"
      entity_category: "diagnostic"
      lambda: 'return id(recorded_display_refresh) += 1;'
    
web_server:
  port: 80
  include_internal: True
  version: 3

captive_portal:


# Here is deep sleep part
deep_sleep:
  id: deep_sleep_1
  run_duration: 1min  # Device wake up and run 60s (enough to pull data and update)
  sleep_duration: 30min  # deep sleep for 30m