substitutions:
  name: esp32-bluetooth-proxy-f38818
  friendly_name: Bluetooth Proxy f38818
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 0fzKBPn55LliK65UICP3ztP90zrs56Acw7h7xxCyeZc=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: wifi_signal
    name: Bluetooth F38818 WiFi Signal Sensor"
    update_interval: 60s

web_server:
  port: 80