esphome:
  name: esp32camtestb
  friendly_name: esp32camtestb

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "sItBYequYZQ9WIgB32u1zgPJ/FePZu2SGJ8kERIo074="

ota:
  - platform: esphome
    password: "354b4c92bc5e563ccc26a211445234d1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Camtestb Fallback Hotspot"
    password: "T2RmlA3DHgiT"


switch:
  - platform: gpio
    pin: GPIO04
    id: gpio_04
    name: flashlight
    
  - platform: gpio
    pin: GPIO33
    id: gpio_33
    name: redled
    inverted: true
    
  - platform: gpio
    pin: GPIO13
    id: gpio_13
    name: greenled
    

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: TestBCamera

web_server:
  port: 80

captive_portal:
    
    