esphome:
  name: esp32camtesta

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "84c8a5222915fd1cc5312e9751da285b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Camtesta Fallback Hotspot"
    password: "abidOehGp6ob"



switch:
  - platform: gpio
    pin: GPIO04
    id: gpio_04
    name: flashlight
    
  - platform: gpio
    pin: GPIO33
    id: gpio_33
    name: redled
    inverted: true
    
    

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: CamTest A Camera

sensor:
  - platform: wifi_signal
    name: "esp32camtest1 WiFi Signal Sensor"
    update_interval: 60s
  

web_server:
  port: 80



captive_portal:
    