esphome:
  name: esp32cam222
  friendly_name: esp32cam222

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XPe1SfhL1xD9zBD2udAjPf73Rq2stqqLhoqDKuO1Bho="

ota:
  - platform: esphome
    password: "d0e0d1de9e95e6705293fa8b300948e8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Cam222 Fallback Hotspot"
    password: "wiCwIDO2RpNR"


switch:
  - platform: gpio
    pin: GPIO04
    id: gpio_04
    name: flashlight
    
  - platform: gpio
    pin: GPIO33
    id: gpio_33
    name: redled
    inverted: true

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: Test 222 Camera


web_server:
  port: 80

sensor:
  - platform: uptime
    name: Uptime
    entity_category: "diagnostic"
    update_interval: 300s

  - platform: wifi_signal
    name: "WiFi Signal"
    accuracy_decimals: 1
    entity_category: "diagnostic"
    update_interval: 5s
    filters:
      - exponential_moving_average:
          alpha: 0.05
          send_every: 2
          send_first_at: 2
      - or:
        - throttle: 600s
        - delta: 2


captive_portal:

    
    
    