esphome:
  name: esp32mpu6050a
  on_boot:
    then:
       script.execute: consider_deep_sleep

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "4517677221c08ed25ec146bdc3b6b9d9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Mpu6050A Fallback Hotspot"
    password: "Evo2khrJ7Zji"

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  
globals:
  - id: dryer_delta_accel_x
    type: float
  - id: dryer_delta_accel_y
    type: float
  - id: dryer_delta_accel_z
    type: float
  - id: washer_delta_accel_x
    type: float
  - id: washer_delta_accel_y
    type: float
  - id: washer_delta_accel_z
    type: float
    

# Deep Sleep

deep_sleep:
  id: deep_sleep_control
 # run_duration:  1min
  sleep_duration: 60min


sensor:
  - platform: adc
    pin: GPIO035
    name: "Dryer Battery Volts"
    id: deep_sleep_battery_volts
    update_interval: 10min
    attenuation: auto 
    accuracy_decimals: 3
    internal: false

  - platform: mpu6050
    update_interval: 0.25s
    address: 0x68
    accel_x:
      accuracy_decimals: 1
      name: "Dryer Accel X"
      id: dryer_accel_x
      internal: true
      filters:
        - lambda: |-
            id(dryer_delta_accel_x) = fabsf(id(dryer_accel_x).state - x);
            return(x);
    accel_y:
      accuracy_decimals: 1
      name: "Dryer Accel Y"
      id: dryer_accel_y
      internal: true
      filters:
        - lambda: |-
            id(dryer_delta_accel_y) = fabsf(id(dryer_accel_y).state - x);
            return(x);
    accel_z:
      accuracy_decimals: 1
      name: "Dryer Accel Z"
      id: dryer_accel_z
      internal: true
      filters:
        - lambda: |-
            id(dryer_delta_accel_z) = fabsf(id(dryer_accel_z).state - x);
            return(x);
    temperature:
      name: "Dryer Temperature"
      filters:
        - heartbeat: 60s
        
binary_sensor:
  - platform: homeassistant
    id: dryer_status
    entity_id: input_boolean.dryer_status
    
  - platform: homeassistant
    id: prevent_deep_sleep
    entity_id: input_boolean.prevent_deep_sleep

  - platform: template
    device_class: vibration
    name: "Dryer Vibration"
    id: dryer_vibration
    lambda: |-
      if (isnan(id(dryer_delta_accel_x)) or isnan(id(dryer_delta_accel_y)) or isnan(id(dryer_delta_accel_z))) {
        id(dryer).publish_state("Idle");
        return {};
      }
      else if (abs(id(dryer_delta_accel_x)) > 0.9 or abs(id(dryer_delta_accel_y)) > 0.9 or abs(id(dryer_delta_accel_z)) > 0.9) {
        return(true);
      } else {
        return(false);
      }
    filters:
      - delayed_on: 3sec
      - delayed_off: 5min
    on_press:
      then:
        - text_sensor.template.publish:
            id: dryer
            state: Drying
            
    on_release:
      then:
        - text_sensor.template.publish:
            id: dryer
            state: Idle
            
text_sensor:
  - platform: template
    icon: mdi:tumble-dryer
    name: Dryer
    id: dryer

script:
  - id: consider_deep_sleep
    mode: queued
    then:
      - delay: 1min
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep
          then:
            - logger.log: 'Skipping sleep, per prevent_deep_sleep'
          else:
            - deep_sleep.enter: deep_sleep_control
      - script.execute: consider_deep_sleep


captive_portal:
    