# ==============================================================================
#  PROJECT: 5-Inch TFT Display (ESP32-S3) - STABILITY & UI OVERHAUL
#  DATE:    February 24, 2026
#  STATUS:  STABLE (ESPHome 2026.1.5 / ESP-IDF 5.5.1)
# ==============================================================================
#
#  TECHNICAL POST-MORTEM & UI LOG
#  -----------------------------------------------------------------------------
#  1. MEMORY MANAGEMENT (CRITICAL FOR RGB DISPLAYS)
#     - High-Res Display (800x480 RGB): Massive frame buffer requires PSRAM, 
#       but display controller (LCD_CAM) needs internal DMA descriptors.
#     - Fix: Force Wi-Fi and Encryption buffers into PSRAM to free Internal SRAM.
#     - Fix: Disable Hardware AES/SHA to use Software versions in PSRAM.
#     - Fix: Reduced CPU Cache to 32KB to reclaim 32KB Internal SRAM.
#
#  2. UI EVOLUTION 
#     - Navigation: Standardized to 40px height with Material Symbols Outlined.
#     - Typography: Integrated Montserrat 20 for weather and unscii_16 for date/time.
#     - Clock: Added 60 minor ticks and 12 major ticks for standard watch face.
#     - Scales: Standardized temperature (0-120), humidity (0-100), and barometer (28-31)
#       to use 1:1 human-readable increments. Removed x10 math from lambdas.
#     - Buffer: Retained 25% LVGL buffer for display stability vs 10% on Waveshare.
# ==============================================================================

esphome:
  name: fiveinchtft1
  friendly_name: fiveinchtft1
  platformio_options:
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: 5.5.1
    sdkconfig_options:
      # CPU & Cache Optimization (Frees 32KB Internal SRAM)
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_32KB: y
      
      # PSRAM Performance
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      
      # CRITICAL MEMORY RELOCATION SETTINGS
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: y
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: y
      
      # Disable Hardware Crypto (Forces SW Crypto -> Uses PSRAM instead of Internal DMA)
      CONFIG_MBEDTLS_HARDWARE_AES: n
      CONFIG_MBEDTLS_HARDWARE_MPI: n
      CONFIG_MBEDTLS_HARDWARE_SHA: n

psram:
  mode: octal
  speed: 80MHz

# Logging
logger:
  level: DEBUG
  hardware_uart: UART0
  baud_rate: 115200 

# Home Assistant API
api:
  encryption:
    key: "4Ik5aQ+Jzwo/z6hKL4HyUgQa/mmr7MyGZxm64OUG2Cc="

ota:
  - platform: esphome
    password: "6db8fec4e83c4bcb1f86a410c0d0016e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true 
  power_save_mode: NONE
  reboot_timeout: 0s 

  on_connect:
    - component.update: my_online_image

  ap:
    ssid: "Fiveinchtft1 Fallback Hotspot"
    password: "3Ps5BAJqCVne"

captive_portal:

# Display Configuration (RPI-DPI-RGB)
display:
  - platform: rpi_dpi_rgb
    id: main_display
    color_order: RGB
    invert_colors: True
    update_interval: never
    auto_clear_enabled: false
    dimensions:
      width: 800
      height: 480
    de_pin: 40
    hsync_pin: 39
    vsync_pin: 41
    pclk_pin: 0
    pclk_frequency: 12MHz
    data_pins:
      red:   [45, 48, 47, 21, 14]
      green: [5, 6, 7, 15, 16, 4]
      blue:  [8, 3, 46, 9, 1]

# I2C and Touchscreen
i2c:
  sda: GPIO19
  scl: GPIO20
  scan: true

touchscreen:
  platform: gt911
  id: main_touchscreen
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d", touch.x, touch.y, touch.x_raw, touch.y_raw);

# Hardware PWM for Backlight
output:
  - platform: ledc
    pin: 2
    frequency: 1220
    id: gpio_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    id: back_light
    restore_mode: ALWAYS_ON

# Time and Date
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago
    on_time_sync:
      - script.execute: time_update
      - if:
          condition:
            lambda: 'return id(device_last_restart).state == "";'
          then:
            - text_sensor.template.publish:
                id: device_last_restart
                state: !lambda 'return id(homeassistant_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
    on_time:
      - seconds: "*"
        then:
          - script.execute: time_update

# ---------------------------------------------------------
# UI & FONTS
# ---------------------------------------------------------
font:
  - file: "gfonts://Montserrat"
    id: montserrat_20
    size: 20
  - file: "gfonts://Montserrat"
    id: unscii_16
    size: 16
  - file: "gfonts://Material Symbols Outlined"
    id: icon_font
    size: 32
    glyphs: "\uE0F0\uE5C4\uE88A\uE8AC\uE5C8"

script:
  - id: time_update
    then:
      - lvgl.indicator.update:
          id: second_hand
          value: !lambda return id(homeassistant_time).now().second;
      - lvgl.indicator.update:
          id: minute_hand
          value: !lambda return id(homeassistant_time).now().minute;
      - lvgl.indicator.update:
          id: hour_hand
          value: !lambda |-
            auto now = id(homeassistant_time).now();
            return std::fmod(now.hour, 12) * 60 + now.minute;
      - lvgl.label.update:
          id: date_label
          text: !lambda |-
            static const char * const mon_names[] = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
            static char date_buf[16];
            auto now = id(homeassistant_time).now();
            snprintf(date_buf, sizeof(date_buf), "%s %2d", mon_names[now.month-1], now.day_of_month);
            return date_buf;
      - lvgl.label.update:
          id: day_label
          text: !lambda |-
            static const char * const day_names[] = {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"};
            return day_names[id(homeassistant_time).now().day_of_week - 1];

http_request:
  verify_ssl: False
  timeout: 10s

online_image:
  - url: "http://homeassistant.local:8123/local/Paris800_480.png"
    format: png
    id: my_online_image
    type: RGB565
    resize: 800x480
    on_download_finished:
      lvgl.image.update:
        id: first_image
        src: my_online_image

image:
  - file: bulb.png
    id: Paris_image
    resize: 750x420
    type: RGB565

# ---------------------------------------------------------
# LVGL & UI PAGES
# ---------------------------------------------------------
lvgl:
  buffer_size: 25% # Stable for 5" TFT
  style_definitions:
    - id: header_footer
      text_font: icon_font
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_width: 0
      radius: 0
      pad_all: 0
      text_color: 0xFFFFFF
      width: 100%
      height: 40
    - id: date_style
      text_font: unscii_16
      align: center
      text_color: 0x000000

  pages:
    - id: main_page
      widgets:
          - image:
              src: Paris_image
              align: CENTER
              id: first_image

    - id: meter_page_1
      widgets:
          - meter:
              align: LEFT_MID
              height: 350
              width: 350
              scales:
                - range_from: 0
                  range_to: 120
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 2
                    count: 61
                    length: 10
                    color: 0x000000
                    major: {stride: 5, width: 3, length: 15, color: 0xFF0000}
                  indicators:
                    - line: {id: temperature_needle, width: 2, color: 0xFF0000}
              widgets:
                - label: {id: temperature_text, text: "-.- F", align: CENTER, y: 45}
                - label: {text: "Inside Temp", align: CENTER, y: 65}
          - meter:
              align: RIGHT_MID
              height: 350
              width: 350
              scales:
                - range_from: 0
                  range_to: 100
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 2
                    count: 21
                    length: 10
                    color: 0x000000
                    major: {stride: 2, width: 3, length: 15, color: 0xFF0000}
                  indicators:
                    - line: {id: humidity_needle, width: 2, color: 0xFF0000}
              widgets:
                - label: {id: humidity_text, text: "-.- %", align: CENTER, y: 45}
                - label: {text: "Inside Humidity", align: CENTER, y: 65}

    - id: meter_page_2
      widgets:
          - meter:
              align: LEFT_MID
              height: 350
              width: 350
              scales:
                - range_from: 0
                  range_to: 120
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 2
                    count: 61
                    length: 10
                    color: 0x000000
                    major: {stride: 5, width: 3, length: 15, color: 0xFF0000}
                  indicators:
                    - line: {id: temperature_needle_2, width: 2, color: 0xFF0000}
              widgets:
                - label: {id: temperature_text_2, text: "-.- F", align: CENTER, y: 45}
                - label: {text: "Outside Temp", align: CENTER, y: 65}
          - meter:
              align: RIGHT_MID
              height: 350
              width: 350
              scales:
                - range_from: 0
                  range_to: 100
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 2
                    count: 21
                    length: 10
                    color: 0x000000
                    major: {stride: 2, width: 3, length: 15, color: 0xFF0000}
                  indicators:
                    - line: {id: humidity_needle_2, width: 2, color: 0xFF0000}
              widgets:
                - label: {id: humidity_text_2, text: "-.- %", align: CENTER, y: 45}
                - label: {text: "Outside Humidity", align: CENTER, y: 65}

    - id: meter_page_3
      bg_color: Black
      widgets:
        - meter:
            align: CENTER
            height: 400
            width: 400
            scales:
              - range_from: 28
                range_to: 31
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 31
                  length: 10
                  color: 0x0000FF
                  major: {stride: 10, width: 3, length: 15, color: 0xFFFFFF}
                indicators:
                  - line: {id: barometer_needle, width: 4, color: 0xFF0000}
        - label: {id: barometer_text, styles: date_style, text: "inHg", align: CENTER, y: 85, text_color: White}
        - label: {styles: date_style, text: "Barometer", align: CENTER, y: 65, text_color: White}

    - id: clock_page
      bg_color: Black
      widgets:
        - meter:
            id: analog_clock
            height: 400
            width: 400
            align: CENTER
            bg_color: White
            border_width: 0
            outline_width: 0
            scales:
              - range_from: 0
                range_to: 60
                angle_range: 360
                rotation: 270
                ticks:
                  width: 2
                  count: 60
                  length: 10
                  color: 0x555555
                  major: {stride: 5, width: 4, length: 15, color: 0x000000}
                indicators:
                  - line: {id: minute_hand, width: 4, color: 0x000000, r_mod: -15}
                  - line: {id: second_hand, width: 2, color: 0xFF0000, r_mod: -5}
              - range_from: 0
                range_to: 720
                angle_range: 360
                rotation: 270
                indicators:
                  - line: {id: hour_hand, width: 6, color: 0x000000, r_mod: -45}
            widgets:
              - label: {id: day_label, styles: date_style, align: CENTER, y: -60}
              - label: {id: date_label, styles: date_style, align: CENTER, y: 60}

    - id: weather_page
      bg_color: Silver
      widgets:
        - label: {id: current_weather_label_dt0, x: 70, y: 20, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label, x: 40, y: 40, height: 170, width: 320, text_font: montserrat_20, text: '...'}
        - label: {id: current_weather_label_dt1, x: 460, y: 20, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label_1, x: 440, y: 40, height: 170, width: 320, text_font: montserrat_20, text: '...'}
        - label: {id: current_weather_label_dt2, x: 70, y: 240, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label_2, x: 40, y: 260, height: 170, width: 320, text_font: montserrat_20, text: '...'}
        - label: {id: current_weather_label_dt3, x: 460, y: 240, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label_3, x: 440, y: 260, height: 170, width: 320, text_font: montserrat_20, text: '...'}

  top_layer:
    widgets:
      - obj:
          align: bottom_mid
          width: 100%
          height: 40
          bg_color: 0x2F8CD8
          bg_opa: COVER
          border_width: 0
          pad_all: 0
          widgets:
            - buttonmatrix:
                align: CENTER
                width: 100%
                height: 100%
                styles: header_footer
                id: nav_bar
                rows:
                  - buttons:
                    - text: "\uE0F0" # Material Icon: Light On
                      on_press: {then: [light.turn_on: back_light]}
                    - text: "\uE5C4" # Material Icon: Prev
                      on_press: {then: [lvgl.page.previous: ]}
                    - text: "\uE88A" # Material Icon: Home
                      on_press: {then: [lvgl.page.show: main_page]}
                    - text: "\uE8AC" # Material Icon: Light Off
                      on_press: {then: [light.turn_off: back_light]}
                    - text: "\uE5C8" # Material Icon: Next
                      on_press: {then: [lvgl.page.next: ]}

# ---------------------------------------------------------
# SENSORS (TEXT & DATA)
# ---------------------------------------------------------
text_sensor:
  - platform: version
    id: esphome_version
    name: "ESPHome Version"
  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic

  # Weather Forecast Text (From Home Assistant)
  - platform: homeassistant
    id: extraweatherforecast0
    entity_id: input_text.text_nws_extra_forecast
    on_value:
      then:
        lvgl.textarea.update: {id: current_weather_label, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherdatetime0
    entity_id: input_text.text_nws_extra_datetime_0
    on_value:
      then:
        lvgl.label.update: {id: current_weather_label_dt0, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherforecast1
    entity_id: input_text.text_nws_extra_forecast_1
    on_value:
      then:
        lvgl.textarea.update: {id: current_weather_label_1, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherdatetime1
    entity_id: input_text.text_nws_extra_datetime_1
    on_value:
      then:
        lvgl.label.update: {id: current_weather_label_dt1, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherforecast2
    entity_id: input_text.text_nws_extra_forecast_2
    on_value:
      then:
        lvgl.textarea.update: {id: current_weather_label_2, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherdatetime2
    entity_id: input_text.text_nws_extra_datetime_2
    on_value:
      then:
        lvgl.label.update: {id: current_weather_label_dt2, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherforecast3
    entity_id: input_text.text_nws_extra_forecast_3
    on_value:
      then:
        lvgl.textarea.update: {id: current_weather_label_3, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherdatetime3
    entity_id: input_text.text_nws_extra_datetime_3
    on_value:
      then:
        lvgl.label.update: {id: current_weather_label_dt3, text: !lambda 'return x.c_str();'}

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: "FiveInch WiFi Signal Sensor"
    update_interval: 60s

  # Environment Sensors
  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.devtest2_bme280_temperature_devtest2
    on_value:
      - lvgl.indicator.update: {id: temperature_needle, value: !lambda return x;}
      - lvgl.label.update: {id: temperature_text, text: {format: "%.1f°F", args: [ 'x' ]}}

  - platform: homeassistant 
    id: inside_humidity
    entity_id: sensor.devtest2_bme280_humidity_devtest2
    on_value:
      - lvgl.indicator.update: {id: humidity_needle, value: !lambda return x;}
      - lvgl.label.update: {id: humidity_text, text: {format: "%.1f%%", args: [ 'x' ]}}

  - platform: homeassistant
    id: outside_temperature
    entity_id: sensor.tempcurrent
    on_value:
      - lvgl.indicator.update: {id: temperature_needle_2, value: !lambda return x;}
      - lvgl.label.update: {id: temperature_text_2, text: {format: "%.1f°F", args: [ 'x' ]}}

  - platform: homeassistant 
    id: outside_humidity
    entity_id: sensor.humiditycurrent
    on_value:
      - lvgl.indicator.update: {id: humidity_needle_2, value: !lambda return x;}
      - lvgl.label.update: {id: humidity_text_2, text: {format: "%.1f%%", args: [ 'x' ]}}

  - platform: homeassistant
    id: barometer_pressure
    entity_id: sensor.pressurecurrent
    on_value:   
      - lvgl.indicator.update: {id: barometer_needle, value: !lambda 'return x;'}
      - lvgl.label.update: {id: barometer_text, text: {format: "%.1finHG", args: ['x']}}

# Buttons
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"
  - platform: template
    name: "Next Page"
    on_press:
      then:
        - lvgl.page.next
  - platform: template
    name: "Previous Page"
    on_press:
      then:
        - lvgl.page.previous

web_server:
  port: 80
  include_internal: True
  version: 3
