esphome:
  name: fiveinchtft1
  friendly_name: fiveinchtft1

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: 5.2.2
    platform_version: 6.7.0

psram:
  mode: octal
  speed: 80000000.0    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4Ik5aQ+Jzwo/z6hKL4HyUgQa/mmr7MyGZxm64OUG2Cc="

ota:
  - platform: esphome
    password: "6db8fec4e83c4bcb1f86a410c0d0016e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fiveinchtft1 Fallback Hotspot"
    password: "3Ps5BAJqCVne"
i2c:
  sda: 19
  scl: 20
  scan: true

display:
  - platform: rpi_dpi_rgb
    id: disp0
    data_pins:
      red:
        - 45
        - 48
        - 47
        - 21
        - 14
      green:
        - 5
        - 6
        - 7
        - 15
        - 16 
        - 4
      blue:
        - 8
        - 3
        - 46
        - 9
        - 1
    de_pin: 40
    hsync_pin: 39
    vsync_pin: 41
    pclk_pin: 0

    hsync_front_porch: 210
    hsync_pulse_width: 4
    hsync_back_porch: 43
    vsync_front_porch: 22
    vsync_pulse_width: 4
    vsync_back_porch: 12

    pclk_inverted: true
    pclk_frequency: 6500000

    color_order: RGB

    auto_clear_enabled: false
    update_interval: 5s
    dimensions:
      width: 800
      height: 480

    show_test_card: true

touchscreen:
  platform: gt911
  id: touch0
  display: disp0
  interrupt_pin: 10

output:
  - platform: ledc
    pin: 2
    id: backlight_pin

light:
  - platform: monochromatic
    output: backlight_pin
    name: "Backlight Level"
    restore_mode: RESTORE_DEFAULT_ON

lvgl:
  buffer_size: 25%
  displays:
    - disp0
  touchscreens:
    - touch0
  pages:
    - id: main_page
      widgets:
        - label:
            align: CENTER
            text: 'Lance Rules! Yes he does...'

sensor:
  - platform: wifi_signal
    name: "FiveInchTFT WiFi Signal Sensor"
    update_interval: 60s

  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.first_air_quality_monitor_temperature

  - platform: homeassistant  
    id: inside_humidity
    entity_id: sensor.first_air_quality_monitor_humidity

  - platform: uptime
    type: seconds
    name: Uptime Sensor
 
# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"


web_server:
  port: 80
  include_internal: True
  version: 2

captive_portal:
    
