esphome:
  name: freenove-cam-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dMC7H6IE/2TNwhwVJ+7GdVgdNPr17Cfh+q3vb/usLBc="

ota:
  platform: esphome
  password: "f54acefcb7f585f6ba7a610dea5ebf86"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Freenove-Cam-1 Fallback Hotspot"
    password: "LkpDs85DU8kV"

# From https://randomnerdtutorials.com/getting-started-freenove-esp32-wrover-cam/

esp32_camera:
  name: My Camera Freenove 1
  external_clock:
    pin: GPIO21
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO4, GPIO5, GPIO18, GPIO19, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22

  resolution: 640X480
  vertical_flip: false
  horizontal_mirror: false


web_server:
  port: 80

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

captive_portal:
    