
esphome:
  name: freenov-cam-4
  friendly_name: freenov-cam-4

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "uFzLZc/5UnrIerSjKtgGHMqSnYxKgUTiN5BYdPvOACI="

ota:
  platform: esphome
  password: "637899471f8fc35a8a268b8d82940eb8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Freenov-Cam-4 Fallback Hotspot"
    password: "hTivQHrrpcKL"

external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome_custom_components
    components: [ esp32_camera ]

psram:
  mode: octal
  speed: 80MHz

esp32_camera:
  name: 'frenovcam1'
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13

 # http server setting
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

web_server:
  port: 80

sensor:
  
  - platform: wifi_signal
    name: 
      Freenove Cam 4 WiFi Signal Sensor"
    update_interval: 60s 

captive_portal:
    