esphome:
  name: freenove-cam-5
  friendly_name: freenove-cam-5

esp32:
  board: esp32-s3-cam-lcd
  framework:
    type: esp-idf
  variant: esp32s3

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "HAFgLP131z563E4V5jwD7cB6PvxJeYxbbAfY2CQ3krM="

ota:
  password: "8c4cfbc1beb816b5bc8bb1fe582a4c86"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Freenove-Cam-5 Fallback Hotspot"
    password: "5rjTvENDHaFv"

web_server:
  port: 80

sensor:
  
  - platform: wifi_signal
    name: 
      Freenove Cam 5 WiFi Signal Sensor"
    update_interval: 60s 



captive_portal:
    