esphome:
  name: freezer-relay
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TTnz82t3lKyFJXjxYDR2bZdGXFayj2dg/MVSaBjj4S0="

ota:
  platform: esphome
  password: "e3612d70d8e9418a19a1f6a068eca154"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Freezer-Relay Fallback Hotspot"
    password: "f4UWvC0CWYyA"


esp32_ble_tracker:

sensor:
  - platform: inkbird_ibsth1_mini
    mac_address: 49:42:08:00:53:6A
    temperature:
      name: "Inkbird IBS-TH1 Mini Temperature"
    humidity:
      name: "Inkbird IBS-TH1 Mini Humidity"
    battery_level:
      name: "Inkbird IBS-TH1 Mini Battery Level"

web_server:
  port: 80

captive_portal:
