esphome:
  name: ldhtest1
  friendly_name: ldhtest1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "kC2/8XQL8IgBlrV7tjAbvpivNa7o/jr1QoEdhC3upFo="

ota:
  password: "c8eb394cb4fb426e8852a24b32e35867"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ldhtest1 Fallback Hotspot"
    password: "Ya9jZSTWVCAI"

captive_portal:
    