esphome:
  name: melife-oled

esp32:
  board: esp32dev
  framework:
    type: arduino

time:
  - platform: homeassistant
    id: esptime

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "437ff6e754489c6ad9a0264afbd9e0b1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Melife-Oled Fallback Hotspot"
    password: "la9QyjgqSdn9"

font:
  - file: 'FreeMono.ttf'
    id: font1
    size: 15

  
i2c:
  sda: 5
  scl: 4
  scan: True
  frequency: 400kHz


display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    update_interval: 1s
    lambda: |-

      it.strftime(0, 30, id(font1), "%I %M %S %p",  id(esptime).now());
      it.strftime(0, 45, id(font1), "%a %d %b %y",  id(esptime).now());
      if (id(inside_temperature).has_state()) {
        it.printf(0, 0, id(font1), "%.1f°", id(inside_temperature).state);
        it.printf(70, 0, id(font1), "%.1f%%", id(inside_humidity).state);
        }

  
      

sensor:
  - platform: wifi_signal
    name: "esp32camtest1 WiFi Signal Sensor"
    update_interval: 60s

  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.first_air_quality_monitor_temperature

  - platform: homeassistant  
    id: inside_humidity
    entity_id: sensor.first_air_quality_monitor_humidity
  

web_server:
  port: 80


captive_portal:
    