esphome:
  name: melife-oled

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "437ff6e754489c6ad9a0264afbd9e0b1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Melife-Oled Fallback Hotspot"
    password: "la9QyjgqSdn9"

font:
  - file: 'FreeMono.ttf'
    id: font1
    size: 18
  
i2c:
  sda: 5
  scl: 4
  scan: false

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.printf(64, 20, id(font1), TextAlign::TOP_CENTER, "Hello Judi!");

sensor:
  - platform: wifi_signal
    name: "esp32camtest1 WiFi Signal Sensor"
    update_interval: 60s
  

web_server:
  port: 80


captive_portal:
    