esphome:
  name: oled-test1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "cb08aa3125167dbd79644096ab2e1c90"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Oled-Test1 Fallback Hotspot"
    password: "iQYL9cKH7rTX"
    
time:
  - platform: homeassistant
    id: esptime

font:
  - file: 'FreeMono.ttf'
    id: font1
    size: 12
  
i2c:
  sda: 21
  scl: 22
  scan: false

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "How Now Brown Cow");  
      it.strftime(40, 50, id(font1), "%H:%M:%S", id(esptime).now());
captive_portal:
    