esphome:
  name: s3devkitctest2
  friendly_name: s3devkitctest2

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8qY2WtPC+fER6WCaGS5GfLpkBDKww/h3WDl9j+5cf78="

ota:
  - platform: esphome
    password: "2c700ecd2c40d8658fffd7dbff1c4083"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S3Devkitctest2 Fallback Hotspot"
    password: "lBtw8AyriywF"

web_server:
  port: 80

captive_portal:
    