esphome:
  name: sensor-node-2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Bluetooth Tracker          
esp32_ble_tracker:

sensor:
  - platform: dht
    pin: GPIO23
    temperature:
      name: "Garage Temperature"
    humidity:
      name: "Garage Humidity"
    update_interval: 60s

  - platform: inkbird_ibsth1_mini
    mac_address: 49:42:08:00:53:6A
    temperature:
      name: "Inkbird IBS-TH1 Mini Temperature"
    humidity:
      name: "Inkbird IBS-TH1 Mini Humidity"
    battery_level:
      name: "Inkbird IBS-TH1 Mini Battery Level"

  - platform: wifi_signal
    name: "Garage WiFi Signal Sensor"
    update_interval: 60s


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TTnz82t3lKyFJXjxYDR2bZdGXFayj2dg/MVSaBjj4S0="

ota:
  platform: esphome
  password: "4fa43852ed641556f4459886d0a6e34a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor-Node-2 Fallback Hotspot"
    password: "Y151Wm0ZnS9c"


web_server:
  port: 80


captive_portal:
