esphome:
  name: sensor-node-5

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TTnz82t3lKyFJXjxYDR2bZdGXFayj2dg/MVSaBjj4S0="
    
ota:
  password: "d98ca5c460f99e1f4f9cb84e4a89b637"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor-Node-5 Fallback Hotspot"
    password: "kDKc1uB9hzVf"

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a


sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature 2"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure 2"
      filters:
          - offset: 31
    humidity:
      name: "BME280 Humidity 2"
    address: 0x76
    update_interval: 60s



captive_portal:
    