#https://community.home-assistant.io/t/elecrow-crowpanel-7-with-esphome/768501/5
esphome:
  name: seveninchtft1
  friendly_name: seveninchtft1
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    platform_version: 6.8.1
    version: 5.3.0
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: UART0

# Enable Home Assistant API
api:
  encryption:
    key: "AIVcSJre4VDwfHstCkkhxkilrCNsO9sJMXEGRMJl5Ic="

ota:
  - platform: esphome
    password: "5938816d31d547c3fc3f7d2db85070ae"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Seveninchtft1 Fallback Hotspot"
    password: "b24fNfY6UZFm"


i2c:
  sda: 19
  scl: 20

display:
  - platform: rpi_dpi_rgb
    data_pins:
      red: [14, 21, 47, 48, 45]
      green: [9, 46, 3, 8, 16, 1]
      blue: [15, 7, 6, 5, 4]
    de_pin: 41
    hsync_pin: 39
    vsync_pin: 40
    pclk_pin: 0
    hsync_front_porch: 40
    hsync_pulse_width: 48
    hsync_back_porch: 13
    vsync_front_porch: 1
    vsync_pulse_width: 31
    vsync_back_porch: 13
    pclk_inverted: true
    pclk_frequency: 15MHz
    color_order: RGB
    auto_clear_enabled: false
    update_interval: never
    dimensions:
      width: 800
      height: 480

touchscreen:
  platform: gt911
  interrupt_pin: 38

output:
  - platform: ledc
    pin: 2
    id: backlight_pin

light:
  - platform: monochromatic
    output: backlight_pin
    name: "Backlight Level"
    restore_mode: RESTORE_DEFAULT_ON
    gamma_correct: 1.8

lvgl:
  color_depth: 16
  bg_color: 0
  border_width: 0
  outline_width: 0
  shadow_width: 0
  text_font: unscii_16
  align: center
  style_definitions:
    - id: meter_style
      border_width: 0
      outline_width: 0
      align: center
      bg_color: 0
    - id: title_style
      text_font: MONTSERRAT_40
      align: center
      text_color: 0xFFFFFF
      bg_opa: TRANSP
      bg_color: 0
      radius: 4
      pad_all: 2
    - id: detail_style
      text_font: MONTSERRAT_18
      align: center
      text_color: 0xFFFFFF
      bg_opa: TRANSP
      bg_color: 0
      radius: 4
      pad_all: 2
  pages:
      - id: meter_page
        widgets:
          - meter:
              align: LEFT_MID
              height: 350
              width: 350
              scales:
                - range_from: 00 # scale for the needle value
                  range_to: 1000
                  angle_range: 240
                  rotation: 150
                  indicators:
                    - line:
                        id: temperature_needle
                        width: 2
                        color: 0xFF0000
                        r_mod: -4
                    - tick_style:
                        start_value: 0
                        end_value: 100
                        color_start: 0x0000bd
                        color_end: 0xbd0000
                        width: 1
                - range_from: 0 # scale for the value labels
                  range_to: 100
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 1
                    count: 51
                    length: 10
                    color: 0x000000
                    major:
                      stride: 5
                      width: 2
                      length: 10
                      color: 0x404040
                      label_gap: 10
              widgets:
                - label:
                    id: temperature_text
                    text: "-.- F"
                    align: CENTER
                    y: 45
                - label:
                    text: "Temp"
                    align: CENTER
                    y: 65


          - meter:
              align: RIGHT_MID
              height: 350
              width: 350
              scales:
                - range_from: 00 # scale for the needle value
                  range_to: 1000
                  angle_range: 240
                  rotation: 150
                  indicators:
                    - line:
                        id: humidity_needle
                        width: 2
                        color: 0xFF0000
                        r_mod: -4
                    - tick_style:
                        start_value: 0
                        end_value: 100
                        color_start: 0x0000bd
                        color_end: 0xbd0000
                        width: 1
                - range_from: 0 # scale for the value labels
                  range_to: 100
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 1
                    count: 51
                    length: 10
                    color: 0x000000
                    major:
                      stride: 5
                      width: 2
                      length: 10
                      color: 0x404040
                      label_gap: 10
              widgets:
                - label:
                    id: humidity_text
                    text: "-.- %"
                    align: CENTER
                    y: 45
                - label:
                    text: "Humidity"
                    align: CENTER
                    y: 65


sensor:
  - platform: wifi_signal
    name: "seveninchtft1 WiFi Signal Sensor"
    update_interval: 60s

  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.first_air_quality_monitor_temperature
    on_value:
      - lvgl.indicator.update:
          id: temperature_needle
          value: !lambda return x * 10;
      - lvgl.label.update:
          id: temperature_text
          text:
            format: "%.1f°F"
            args: [ 'x' ]


  - platform: homeassistant  
    id: inside_humidity
    entity_id: sensor.first_air_quality_monitor_humidity
    on_value:
      - lvgl.indicator.update:
          id: humidity_needle
          value: !lambda return x * 10;
      - lvgl.label.update:
          id: humidity_text
          text:
            format: "%.1f%%"
            args: [ 'x' ]
  
  - platform: uptime
    type: seconds
    name: Uptime Sensor

text_sensor:
  - platform: version
    name: "ESPHome Version" 

 
# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"  

web_server:
  port: 80
  include_internal: True
  version: 3

captive_portal:
    
