# ==============================================================================
#  ELECROW CROWPANEL 7.0" (ESP32-S3) - FIXED UI SCALES & SENSORS
#  DATE: February 24, 2026
# ==============================================================================
#  Hardware: Elecrow CrowPanel 7.0" HMI Display (ESP32-S3)
#  ESPHome Version: 2026.1.5
#
#  KEY FIXES & FEATURES IN THIS CONFIGURATION:
#  1. Touch Screen (GT911): The `interrupt_pin: 38` was removed. Forcing the 
#     GT911 into polling mode prevents complete touch unresponsiveness and 
#     avoids hardware interrupt handling issues on this specific board.
#  2. Framework Version: Removed manual ESP-IDF version pinning. Allowing ESPHome 
#     2026.1.5 to use its default ESP-IDF (5.4.2+) resolves strict I2C 
#     compilation errors.
#  3. Web Server Dashboard: Added explicit `name:` fields to all Home Assistant 
#     sensors. Without a name, imported sensors remain internal and are hidden 
#     from the local ESPHome web UI.
#  4. Dynamic Boot Image: Starts on 'main_page' with a local bulb image, 
#     then downloads and hot-swaps to a high-res Paris photo upon WiFi connect.
#  5. UI Updates: 
#     - Navigation: Reverted to a seamless, edge-to-edge LVGL `buttonmatrix`.
#     - Clock: Added 60 minor ticks and 12 major ticks for standard watch face.
#     - Scales: Standardized temperature (0-120), humidity (0-100), and barometer (28-31)
#       to use 1:1 human-readable increments. Removed x10 math from lambdas.
# ==============================================================================

esphome:
  name: seveninchtft1
  friendly_name: seveninchtft1
  platformio_options:
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
  on_boot:
    priority: -10
    then:
      - lvgl.page.show: main_page

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG
  hardware_uart: UART0

api:
  encryption:
    key: "AIVcSJre4VDwfHstCkkhxkilrCNsO9sJMXEGRMJl5Ic="

ota:
  - platform: esphome
    password: "5938816d31d547c3fc3f7d2db85070ae"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  on_connect:
    - component.update: my_online_image
  ap:
    ssid: "Seveninchtft1 Fallback Hotspot"
    password: "b24fNfY6UZFm"

i2c:
  sda: 19
  scl: 20

display:
  - platform: rpi_dpi_rgb
    data_pins:
      red: [14, 21, 47, 48, 45]
      green: [9, 46, 3, 8, 16, 1]
      blue: [15, 7, 6, 5, 4]
    de_pin: 41
    hsync_pin: 39
    vsync_pin: 40
    pclk_pin: 0
    hsync_front_porch: 40
    hsync_pulse_width: 48
    hsync_back_porch: 13
    vsync_front_porch: 1
    vsync_pulse_width: 31
    vsync_back_porch: 13
    pclk_inverted: true
    pclk_frequency: 15MHz
    color_order: RGB
    auto_clear_enabled: false
    update_interval: never
    dimensions:
      width: 800
      height: 480

touchscreen:
  platform: gt911
  id: main_touchscreen
  on_touch:
    - lambda: |-
          ESP_LOGD("cal", "x=%d, y=%d", touch.x, touch.y);

output:
  - platform: ledc
    pin: 2
    id: backlight_pin

light:
  - platform: monochromatic
    output: backlight_pin
    id: lcdbacklight
    name: "Backlight Level"
    restore_mode: RESTORE_DEFAULT_ON
    gamma_correct: 1.8

# ---------------------------------------------------------
# IMAGES & RESOURCES
# ---------------------------------------------------------
http_request:
  verify_ssl: False 

online_image:
  - url: "http://homeassistant.local:8123/local/Paris800_480.png"
    format: png
    id: my_online_image
    type: RGB565
    resize: 800x480
    on_download_finished:
      lvgl.image.update: {id: first_image, src: my_online_image} 

image:
  - file: bulb.png
    id: bulb_image
    resize: 750x420
    type: RGB565 

font:
  - file: "gfonts://Montserrat"
    id: montserrat_16
    size: 16
  - file: "gfonts://Montserrat"
    id: montserrat_20
    size: 20
  - file: "gfonts://Material Symbols Outlined"
    id: icon_font
    size: 32
    glyphs: ["\uE0F0", "\uE5C4", "\uE88A", "\uE8AC", "\uE5C8"]

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago
    on_time:
      - seconds: "*"
        then:
          - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.indicator.update: {id: second_hand, value: !lambda "return id(homeassistant_time).now().second;"}
      - lvgl.indicator.update: {id: minute_hand, value: !lambda "return id(homeassistant_time).now().minute;"}
      - lvgl.indicator.update: {id: hour_hand, value: !lambda "auto now = id(homeassistant_time).now(); return std::fmod(now.hour, 12) * 60 + now.minute;"}
      - lvgl.label.update: 
          id: date_label 
          text: !lambda |-
            static const char * const mon_names[] = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
            static char date_buf[16];
            auto now = id(homeassistant_time).now();
            snprintf(date_buf, sizeof(date_buf), "%s %2d", mon_names[now.month-1], now.day_of_month);
            return date_buf;
      - lvgl.label.update:
          id: day_label
          text: !lambda |-
            static const char * const day_names[] = {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"};
            return day_names[id(homeassistant_time).now().day_of_week - 1];

# ---------------------------------------------------------
# LVGL CONFIGURATION
# ---------------------------------------------------------
lvgl:
  buffer_size: 10%
  color_depth: 16
  style_definitions:
    - id: header_footer
      text_font: icon_font
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_width: 0
      radius: 0
      pad_all: 0
      text_color: 0xFFFFFF
      width: 100%
      height: 45
    - id: date_style
      text_font: montserrat_16
      align: center
      text_color: 0x000000

  pages:
    - id: main_page      
      bg_color: Black
      widgets:
        - image: {src: bulb_image, align: CENTER, id: first_image} 

    - id: clock_page
      bg_color: Black
      widgets:
        - meter:
            id: analog_clock
            height: 400
            width: 400
            align: CENTER
            bg_color: White
            border_width: 0
            outline_width: 0
            scales:
              - range_from: 0
                range_to: 60
                angle_range: 360
                rotation: 270
                ticks:
                  width: 2
                  count: 60
                  length: 10
                  color: 0x555555
                  major: {stride: 5, width: 4, length: 15, color: 0x000000}
                indicators:
                  - line: {id: minute_hand, width: 4, color: 0x000000, r_mod: -15}
                  - line: {id: second_hand, width: 2, color: 0xFF0000, r_mod: -5}
              - range_from: 0
                range_to: 720
                angle_range: 360
                rotation: 270
                indicators:
                  - line: {id: hour_hand, width: 6, color: 0x000000, r_mod: -45}
            widgets:
              - label: {id: day_label, styles: date_style, align: CENTER, y: -60}
              - label: {id: date_label, styles: date_style, align: CENTER, y: 60}

    - id: meter_page_1
      widgets:
        - meter:
            align: LEFT_MID
            height: 350
            width: 350
            scales:
              - range_from: 0
                range_to: 120
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 61
                  length: 10
                  color: 0x000000
                  major: {stride: 5, width: 3, length: 15, color: 0xFF0000}
                indicators:
                  - line: {id: temperature_needle, width: 2, color: 0xFF0000}
            widgets:
              - label: {id: temperature_text, text: "-.- F", align: CENTER, y: 45}
              - label: {text: "Inside Temp", align: CENTER, y: 65}
        - meter:
            align: RIGHT_MID
            height: 350
            width: 350
            scales:
              - range_from: 0
                range_to: 100
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 21
                  length: 10
                  color: 0x000000
                  major: {stride: 2, width: 3, length: 15, color: 0xFF0000}
                indicators:
                  - line: {id: humidity_needle, width: 2, color: 0xFF0000}
            widgets:
              - label: {id: humidity_text, text: "-.- %", align: CENTER, y: 45}
              - label: {text: "Inside Humidity", align: CENTER, y: 65}

    - id: meter_page_2
      widgets:
        - meter:
            align: LEFT_MID
            height: 350
            width: 350
            scales:
              - range_from: 0
                range_to: 120
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 61
                  length: 10
                  color: 0x000000
                  major: {stride: 5, width: 3, length: 15, color: 0xFF0000}
                indicators:
                  - line: {id: temperature_needle_2, width: 2, color: 0xFF0000}
            widgets:
              - label: {id: temperature_text_2, text: "-.- F", align: CENTER, y: 45}
              - label: {text: "Outside Temp", align: CENTER, y: 65}
        - meter:
            align: RIGHT_MID
            height: 350
            width: 350
            scales:
              - range_from: 0
                range_to: 100
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 21
                  length: 10
                  color: 0x000000
                  major: {stride: 2, width: 3, length: 15, color: 0xFF0000}
                indicators:
                  - line: {id: humidity_needle_2, width: 2, color: 0xFF0000}
            widgets:
              - label: {id: humidity_text_2, text: "-.- %", align: CENTER, y: 45}
              - label: {text: "Outside Humidity", align: CENTER, y: 65}

    - id: meter_page_3
      bg_color: Black
      widgets:
        - meter:
            align: CENTER
            height: 400
            width: 400
            scales:
              - range_from: 28
                range_to: 31
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 31
                  length: 10
                  color: 0x0000FF
                  major: {stride: 10, width: 3, length: 15, color: 0xFFFFFF}
                indicators:
                  - line: {id: barometer_needle, width: 4, color: 0xFF0000}
        - label: {id: barometer_text, styles: date_style, text: "inHg", align: CENTER, y: 85}
        - label: {styles: date_style, text: "Barometer", align: CENTER, y: 65}

    - id: weather_page
      bg_color: Silver
      widgets:
        - label: {id: current_weather_label_dt0, x: 70, y: 20, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label, x: 40, y: 40, height: 170, width: 320, text_font: montserrat_16, text: '...'}
        - label: {id: current_weather_label_dt1, x: 460, y: 20, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label_1, x: 440, y: 40, height: 170, width: 320, text_font: montserrat_16, text: '...'}
        - label: {id: current_weather_label_dt2, x: 70, y: 240, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label_2, x: 40, y: 260, height: 170, width: 320, text_font: montserrat_16, text: '...'}
        - label: {id: current_weather_label_dt3, x: 460, y: 240, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label_3, x: 440, y: 260, height: 170, width: 320, text_font: montserrat_16, text: '...'}

  top_layer:
    widgets:
      - obj:
          align: BOTTOM_MID
          width: 100%
          height: 45
          bg_color: 0x2F8CD8
          bg_opa: COVER
          border_width: 0
          pad_all: 0
          widgets:
            - buttonmatrix:
                align: CENTER
                width: 100%
                height: 100%
                styles: header_footer
                id: nav_bar
                rows:
                  - buttons:
                    - text: "\uE0F0" 
                      on_press: {then: [light.turn_on: lcdbacklight]}
                    - text: "\uE5C4" 
                      on_press: {then: [lvgl.page.previous]}
                    - text: "\uE88A" 
                      on_press: {then: [lvgl.page.show: main_page]}
                    - text: "\uE8AC" 
                      on_press: {then: [light.turn_off: lcdbacklight]}
                    - text: "\uE5C8" 
                      on_press: {then: [lvgl.page.next]}

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s 
  - platform: uptime
    name: "Uptime" 

  - platform: homeassistant
    id: inside_temperature
    name: "Inside Temperature"
    entity_id: sensor.devtest2_bme280_temperature_devtest2
    on_value:
      - lvgl.indicator.update: {id: temperature_needle, value: !lambda 'return x;'}
      - lvgl.label.update: {id: temperature_text, text: {format: "%.1f°F", args: ['x']}}

  - platform: homeassistant
    id: inside_humidity
    name: "Inside Humidity"
    entity_id: sensor.devtest2_bme280_humidity_devtest2
    on_value:
      - lvgl.indicator.update: {id: humidity_needle, value: !lambda 'return x;'}
      - lvgl.label.update: {id: humidity_text, text: {format: "%.1f%%", args: ['x']}}

  - platform: homeassistant
    id: outside_temperature
    name: "Outside Temperature"
    entity_id: sensor.tempcurrent
    on_value:
      - lvgl.indicator.update: {id: temperature_needle_2, value: !lambda 'return x;'}
      - lvgl.label.update: {id: temperature_text_2, text: {format: "%.1f°F", args: ['x']}}

  - platform: homeassistant
    id: outside_humidity
    name: "Outside Humidity"
    entity_id: sensor.humiditycurrent
    on_value:
      - lvgl.indicator.update: {id: humidity_needle_2, value: !lambda 'return x;'}
      - lvgl.label.update: {id: humidity_text_2, text: {format: "%.1f%%", args: ['x']}}
          
  - platform: homeassistant
    id: barometer_pressure
    name: "Barometric Pressure"
    entity_id: sensor.pressurecurrent
    on_value:   
      - lvgl.indicator.update: {id: barometer_needle, value: !lambda 'return x;'}
      - lvgl.label.update: {id: barometer_text, text: {format: "%.1finHG", args: ['x']}}

text_sensor:
  - platform: version
    id: esphome_version
    name: "ESPHome Version" 

  - platform: homeassistant
    id: extraweatherforecast0
    name: "Forecast 0"
    entity_id: input_text.text_nws_extra_forecast
    on_value: {then: [lvgl.textarea.update: {id: current_weather_label, text: !lambda 'return x.c_str();'}]}
  - platform: homeassistant
    id: extraweatherdatetime0
    name: "Forecast Time 0"
    entity_id: input_text.text_nws_extra_datetime_0
    on_value: {then: [lvgl.label.update: {id: current_weather_label_dt0, text: !lambda 'return x.c_str();'}]}

  - platform: homeassistant
    id: extraweatherforecast1
    name: "Forecast 1"
    entity_id: input_text.text_nws_extra_forecast_1
    on_value: {then: [lvgl.textarea.update: {id: current_weather_label_1, text: !lambda 'return x.c_str();'}]}
  - platform: homeassistant
    id: extraweatherdatetime1
    name: "Forecast Time 1"
    entity_id: input_text.text_nws_extra_datetime_1
    on_value: {then: [lvgl.label.update: {id: current_weather_label_dt1, text: !lambda 'return x.c_str();'}]}

  - platform: homeassistant
    id: extraweatherforecast2
    name: "Forecast 2"
    entity_id: input_text.text_nws_extra_forecast_2
    on_value: {then: [lvgl.textarea.update: {id: current_weather_label_2, text: !lambda 'return x.c_str();'}]}
  - platform: homeassistant
    id: extraweatherdatetime2
    name: "Forecast Time 2"
    entity_id: input_text.text_nws_extra_datetime_2
    on_value: {then: [lvgl.label.update: {id: current_weather_label_dt2, text: !lambda 'return x.c_str();'}]}

  - platform: homeassistant
    id: extraweatherforecast3
    name: "Forecast 3"
    entity_id: input_text.text_nws_extra_forecast_3
    on_value: {then: [lvgl.textarea.update: {id: current_weather_label_3, text: !lambda 'return x.c_str();'}]}
  - platform: homeassistant
    id: extraweatherdatetime3
    name: "Forecast Time 3"
    entity_id: input_text.text_nws_extra_datetime_3
    on_value: {then: [lvgl.label.update: {id: current_weather_label_dt3, text: !lambda 'return x.c_str();'}]}

# Restart, Safe Mode & WEB NAVIGATION Buttons
button:
  - platform: template
    name: "Next Page"
    icon: "mdi:arrow-right-bold"
    on_press:
      - lvgl.page.next: 

  - platform: template
    name: "Previous Page"
    icon: "mdi:arrow-left-bold"
    on_press:
      - lvgl.page.previous: 

  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode" 

web_server:
  port: 80
  include_internal: true
  version: 3 

captive_portal:
