#https://community.home-assistant.io/t/elecrow-crowpanel-7-with-esphome/768501/5
esphome:
  name: seveninchtft1
  friendly_name: seveninchtft1
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    platform_version: 6.8.1
    version: 5.3.0
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: UART0

# Enable Home Assistant API
api:
  encryption:
    key: "AIVcSJre4VDwfHstCkkhxkilrCNsO9sJMXEGRMJl5Ic="

ota:
  - platform: esphome
    password: "5938816d31d547c3fc3f7d2db85070ae"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Seveninchtft1 Fallback Hotspot"
    password: "b24fNfY6UZFm"


i2c:
  sda: 19
  scl: 20

display:
  - platform: rpi_dpi_rgb
    data_pins:
      red: [14, 21, 47, 48, 45]
      green: [9, 46, 3, 8, 16, 1]
      blue: [15, 7, 6, 5, 4]
    de_pin: 41
    hsync_pin: 39
    vsync_pin: 40
    pclk_pin: 0
    hsync_front_porch: 40
    hsync_pulse_width: 48
    hsync_back_porch: 13
    vsync_front_porch: 1
    vsync_pulse_width: 31
    vsync_back_porch: 13
    pclk_inverted: true
    pclk_frequency: 15MHz
    color_order: RGB
    auto_clear_enabled: false
    update_interval: never
    dimensions:
      width: 800
      height: 480

touchscreen:
  platform: gt911
  interrupt_pin: 38

output:
  - platform: ledc
    pin: 2
    id: backlight_pin

light:
  - platform: monochromatic
    output: backlight_pin
    name: "Backlight Level"
    restore_mode: RESTORE_DEFAULT_ON
    gamma_correct: 1.8

lvgl:


sensor:
  - platform: wifi_signal
    name: "seveninchtft1 WiFi Signal Sensor"
    update_interval: 60s

  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.first_air_quality_monitor_temperature

  - platform: homeassistant  
    id: inside_humidity
    entity_id: sensor.first_air_quality_monitor_humidity
  
  - platform: uptime
    type: seconds
    name: Uptime Sensor

text_sensor:
  - platform: version
    name: "ESPHome Version" 

 
# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"  

web_server:
  port: 80
  include_internal: True



captive_portal:
    
