esphome:
  name: seveninchtft3
  friendly_name: seveninchtft3

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: octal

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hLzQ8yAW0dciREBAFG0XKdXYggo51ev1hucEfTvVscc="

ota:
  - platform: esphome
    password: "c686bc1af3e537282979896151607fb0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Seveninchtft3 Fallback Hotspot"
    password: "fWrUMbFSEi10"

captive_portal:
    
