esphome:
  name: temphold1
  friendly_name: temphold1

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+nrq8HtTSsJv8oVYDOaSK8vQFqlo20c8+aFeT9pVkzI="

ota:
  - platform: esphome
    password: "4883ce5c0414fb4678f73a44fd8c7889"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temphold1 Fallback Hotspot"
    password: "b4ubMKo1K1aU"

web_server:
  port: 80


captive_portal:
    