esphome:
  name: testbuild1
  friendly_name: testbuild1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "vEuLR5E4/v+5DEVbnwyo+HuO2F+YnpgZBGoqOubFarw="

ota:
  - platform: esphome
    password: "780e5d3bce3874b11eb645972c49987b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testbuild1 Fallback Hotspot"
    password: "D0swXyORptTJ"

web_server:
  port: 80

captive_portal:
    