esphome:
  name: ttgo-camera-1

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "10081d1b80488372cf378927020e2243"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ttgo-Camera-1 Fallback Hotspot"
    password: "Dioo2L6cXHdP"
    

binary_sensor:
  - platform: gpio
    pin: 33
    name: "TTGO PIR Sensor"
    device_class: motion

font:
  - file: 'FreeMono.ttf'
    id: font1
    size: 18
  
i2c:
  sda: 21
  scl: 22
  scan: false

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.printf(64, 20, id(font1), TextAlign::TOP_CENTER, "Hello Judi!");

web_server:
  port: 80


captive_portal:
    