# ==============================================================================
#  WAVESHARE ESP32-S3-TOUCH-LCD-4.3 (800x480) - FIXED SCALES
#  DATE: February 24, 2026
# ==============================================================================
#  STATUS: ✅ FUNCTIONAL (Backlight Toggles, UI Works, WiFi Connects)
#  NOTE:   May experience minor "Brownout" resets on cold boot due to immediate
#          screen power-up. This is preferred over a non-working backlight.
#
#  UI UPDATES:
#  - Clock: Fixed analog clock rendering (360 angle, 270 rotation) and proportional 
#    hands to identically match the main UI standard. Removed unnecessary 
#    wrapping object and fixed day/date label alignments.
#  - Scales: Standardized temperature (0-120), humidity (0-100), and barometer (28-31)
#    to use 1:1 human-readable increments.
#
#  -----------------------------------------------------------------------------
#  KNOWN ISSUES & SOLUTIONS LOG
#  -----------------------------------------------------------------------------
#  1. BOOT LOOP / CRASHES (Flash Size Mismatch)
#     Issue:  Device would boot, download image, then crash with "Invalid Address".
#     Cause:  Config was set to 16MB/8MB flash, but bootloader reported 4MB.
#     Fix:    Forced `board_build.flash_size: 4MB`.
#
#  2. BACKLIGHT UNRESPONSIVE (Stuck ON/OFF)
#     Issue:  Web toggle worked logically but physical screen didn't react.
#     Cause:  Conflict between "Safe Boot" logic (forcing OFF) and hardware defaults,
#             plus incorrect clock polarity causing driver noise.
#     Fix:    1. Set `restore_mode: ALWAYS_ON` (Hardware prefers starting ON).
#             2. Set `pclk_inverted: false` (Matches working reference unit).
#             3. Reverted I2C to default settings (No custom timeouts).
#
#  3. BROWNOUT RESETS (Power Dip)
#     Issue:  "Brownout detector was triggered" when screen turns on.
#     Cause:  High inrush current.
#     Fix:    Added `power_save_mode: NONE` to stabilize Wi-Fi current draw.
#             (Note: Use a high-quality short USB cable to fix fully).
#
#  4. WATCHDOG TIMEOUTS / MEMORY CRASH
#     Issue:  "Interrupt wdt timeout" or "Insufficient memory" during image load.
#     Cause:  Large 800x480 PNG decoding used all RAM.
#     Fix:    Reduced LVGL `buffer_size` to 10% to free up Heap/PSRAM.
#
# ==============================================================================

esphome:
  name: wavesharetouch1
  friendly_name: wavesharetouch1
  
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
    board_build.flash_size: 4MB # Critical match for bootloader

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "20"

# ---------------------------------------------------------
# HARDWARE
# ---------------------------------------------------------
psram:
  mode: octal
  speed: 80MHz

i2c:
  sda: 8
  scl: 9
  scan: true
  id: bus_a
  # Reverted to defaults (Standard 100kHz) as this proved most stable
  # for the CH422G on this specific revision.

ch422g:
  - id: io_expander
    i2c_id: bus_a

logger:
  level: DEBUG

# ---------------------------------------------------------
# CONNECTIVITY
# ---------------------------------------------------------
api:
  encryption:
    key: "GhDzPzQcLq3xg9LVDrpIolcR5wu5hg/cDJs7wk1vjqM="

ota:
  - platform: esphome
    password: "cf6d2dd8038bcfc63c9f7c98c15adf17"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # NONE is critical to prevent current spikes causing Brownouts
  power_save_mode: NONE 
  ap:
    ssid: "Waveshare43 Fallback"
    password: "DC8eh1CHRnvt"
  on_connect:
    - component.update: my_online_image

web_server:
  port: 80
  include_internal: True
  version: 3

captive_portal:

# ---------------------------------------------------------
# DISPLAY & TOUCH
# ---------------------------------------------------------
display:
  - platform: rpi_dpi_rgb
    id: my_display
    auto_clear_enabled: false
    invert_colors: true
    color_order: RGB
    dimensions:
      width: 800
      height: 480
    
    pclk_frequency: 14MHz
    pclk_inverted: false # Critical: Must be false for stable operation
    hsync_pulse_width: 4
    hsync_back_porch: 8
    hsync_front_porch: 8
    vsync_pulse_width: 4
    vsync_back_porch: 8
    vsync_front_porch: 8
    
    de_pin: 5
    hsync_pin: 46
    vsync_pin: 3
    pclk_pin: 7
    
    reset_pin:
      ch422g: io_expander
      number: 3

    data_pins:
      red:   [1, 2, 42, 41, 40]
      green: [39, 0, 45, 48, 47, 21]
      blue:  [14, 38, 18, 17, 10]

touchscreen:
  - platform: gt911
    id: my_touch
    i2c_id: bus_a
    interrupt_pin: 4
    reset_pin:
      ch422g: io_expander
      number: 1

# ---------------------------------------------------------
# BACKLIGHT
# ---------------------------------------------------------
switch:
  - platform: gpio
    name: "Backlight Toggle"
    id: backlight_switch
    pin:
      ch422g: io_expander
      number: 2
    # Critical: Hardware prefers starting ON. Forcing OFF at boot caused conflicts.
    restore_mode: ALWAYS_ON 

# ---------------------------------------------------------
# BUTTONS & TIME
# ---------------------------------------------------------
button:
  - platform: restart
    id: restart_device
    name: "Restart Device"

  - platform: template
    name: "Previous Page"
    icon: "mdi:arrow-left-bold"
    on_press:
      - lvgl.page.previous:

  - platform: template
    name: "Next Page"
    icon: "mdi:arrow-right-bold"
    on_press:
      - lvgl.page.next:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago
    on_time:
      - seconds: "*"
        then:
          - script.execute: time_update

# ---------------------------------------------------------
# SENSORS
# ---------------------------------------------------------
text_sensor:
  - platform: version
    id: esphome_version
    name: "ESPHome Version"

  - platform: homeassistant
    id: extraweatherforecast0
    entity_id: input_text.text_nws_extra_forecast
    on_value:
      then:
        lvgl.textarea.update: {id: current_weather_label, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherdatetime0
    entity_id: input_text.text_nws_extra_datetime_0
    on_value:
      then:
        lvgl.label.update: {id: current_weather_label_dt0, text: !lambda 'return x.c_str();'}

  - platform: homeassistant
    id: extraweatherforecast1
    entity_id: input_text.text_nws_extra_forecast_1
    on_value:
      then:
        lvgl.textarea.update: {id: current_weather_label_1, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherdatetime1
    entity_id: input_text.text_nws_extra_datetime_1
    on_value:
      then:
        lvgl.label.update: {id: current_weather_label_dt1, text: !lambda 'return x.c_str();'}

  - platform: homeassistant
    id: extraweatherforecast2
    entity_id: input_text.text_nws_extra_forecast_2
    on_value:
      then:
        lvgl.textarea.update: {id: current_weather_label_2, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherdatetime2
    entity_id: input_text.text_nws_extra_datetime_2
    on_value:
      then:
        lvgl.label.update: {id: current_weather_label_dt2, text: !lambda 'return x.c_str();'}

  - platform: homeassistant
    id: extraweatherforecast3
    entity_id: input_text.text_nws_extra_forecast_3
    on_value:
      then:
        lvgl.textarea.update: {id: current_weather_label_3, text: !lambda 'return x.c_str();'}
  - platform: homeassistant
    id: extraweatherdatetime3
    entity_id: input_text.text_nws_extra_datetime_3
    on_value:
      then:
        lvgl.label.update: {id: current_weather_label_dt3, text: !lambda 'return x.c_str();'}

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"

  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.devtest2_bme280_temperature_devtest2
    on_value:
      - lvgl.indicator.update: {id: temperature_needle, value: !lambda 'return x;'}
      - lvgl.label.update: {id: temperature_text, text: {format: "%.1f°F", args: ['x']}}

  - platform: homeassistant
    id: inside_humidity
    entity_id: sensor.devtest2_bme280_humidity_devtest2
    on_value:
      - lvgl.indicator.update: {id: humidity_needle, value: !lambda 'return x;'}
      - lvgl.label.update: {id: humidity_text, text: {format: "%.1f%%", args: ['x']}}

  - platform: homeassistant
    id: outside_temperature
    entity_id: sensor.tempcurrent
    on_value:
      - lvgl.indicator.update: {id: temperature_needle_2, value: !lambda 'return x;'}
      - lvgl.label.update: {id: temperature_text_2, text: {format: "%.1f°F", args: ['x']}}

  - platform: homeassistant
    id: outside_humidity
    entity_id: sensor.humiditycurrent
    on_value:
      - lvgl.indicator.update: {id: humidity_needle_2, value: !lambda 'return x;'}
      - lvgl.label.update: {id: humidity_text_2, text: {format: "%.1f%%", args: ['x']}}
          
  - platform: homeassistant
    id: barometer_pressure
    entity_id: sensor.pressurecurrent
    on_value:   
      - lvgl.indicator.update: {id: barometer_needle, value: !lambda 'return x;'}
      - lvgl.label.update: {id: barometer_text, text: {format: "%.1finHG", args: ['x']}}

# ---------------------------------------------------------
# UI & GRAPHICS
# ---------------------------------------------------------
http_request:
  verify_ssl: False
  timeout: 10s

online_image:
  - url: "http://homeassistant.local:8123/local/Paris800_480.png"
    format: png
    id: my_online_image
    type: RGB565
    resize: 800x480
    on_download_finished:
      lvgl.image.update: {id: first_image, src: my_online_image}

image:
  - file: bulb.png
    id: Paris_image
    resize: 750x420
    type: RGB565    

font:
  - file: "gfonts://Montserrat"
    id: montserrat_20
    size: 20
  - file: "gfonts://Montserrat"
    id: unscii_16
    size: 16
  - file: "gfonts://Material Symbols Outlined"
    id: icon_font
    size: 32
    glyphs: "\uE0F0\uE5C4\uE88A\uE8AC\uE5C8"

script:
  - id: time_update
    then:
      - lvgl.indicator.update: {id: second_hand, value: !lambda "return id(homeassistant_time).now().second;"}
      - lvgl.indicator.update: {id: minute_hand, value: !lambda "return id(homeassistant_time).now().minute;"}
      - lvgl.indicator.update: {id: hour_hand, value: !lambda "auto now = id(homeassistant_time).now(); return std::fmod(now.hour, 12) * 60 + now.minute;"}
      - lvgl.label.update: 
          id: date_label 
          text: !lambda |-
            static const char * const mon_names[] = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
            static char date_buf[16];
            auto now = id(homeassistant_time).now();
            snprintf(date_buf, sizeof(date_buf), "%s %2d", mon_names[now.month-1], now.day_of_month);
            return date_buf;
      - lvgl.label.update:
          id: day_label
          text: !lambda |-
            static const char * const day_names[] = {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"};
            return day_names[id(homeassistant_time).now().day_of_week - 1];

# ---------------------------------------------------------
# LVGL (10% Buffer to fix RAM Crash)
# ---------------------------------------------------------
lvgl:
  buffer_size: 10%
  style_definitions:
    - id: header_footer
      text_font: icon_font
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_width: 0
      radius: 0
      pad_all: 0
      text_color: 0xFFFFFF
      width: 100%
      height: 40
    - id: date_style
      text_font: unscii_16
      align: center
      text_color: 0x000000

  pages:
    - id: main_page
      widgets:
        - image: {src: Paris_image, align: CENTER, id: first_image}

    - id: meter_page_1
      widgets:
        - meter:
            align: LEFT_MID
            height: 350
            width: 350
            scales:
              - range_from: 0
                range_to: 120
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 61
                  length: 10
                  color: 0x000000
                  major: {stride: 5, width: 3, length: 15, color: 0xFF0000}
                indicators:
                  - line: {id: temperature_needle, width: 2, color: 0xFF0000}
            widgets:
              - label: {id: temperature_text, text: "-.- F", align: CENTER, y: 45}
              - label: {text: "Inside Temp", align: CENTER, y: 65}
        - meter:
            align: RIGHT_MID
            height: 350
            width: 350
            scales:
              - range_from: 0
                range_to: 100
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 21
                  length: 10
                  color: 0x000000
                  major: {stride: 2, width: 3, length: 15, color: 0xFF0000}
                indicators:
                  - line: {id: humidity_needle, width: 2, color: 0xFF0000}
            widgets:
              - label: {id: humidity_text, text: "-.- %", align: CENTER, y: 45}
              - label: {text: "Inside Humidity", align: CENTER, y: 65}

    - id: meter_page_2
      widgets:
        - meter:
            align: LEFT_MID
            height: 350
            width: 350
            scales:
              - range_from: 0
                range_to: 120
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 61
                  length: 10
                  color: 0x000000
                  major: {stride: 5, width: 3, length: 15, color: 0xFF0000}
                indicators:
                  - line: {id: temperature_needle_2, width: 2, color: 0xFF0000}
            widgets:
              - label: {id: temperature_text_2, text: "-.- F", align: CENTER, y: 45}
              - label: {text: "Outside Temp", align: CENTER, y: 65}
        - meter:
            align: RIGHT_MID
            height: 350
            width: 350
            scales:
              - range_from: 0
                range_to: 100
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 21
                  length: 10
                  color: 0x000000
                  major: {stride: 2, width: 3, length: 15, color: 0xFF0000}
                indicators:
                  - line: {id: humidity_needle_2, width: 2, color: 0xFF0000}
            widgets:
              - label: {id: humidity_text_2, text: "-.- %", align: CENTER, y: 45}
              - label: {text: "Outside Humidity", align: CENTER, y: 65}

    - id: meter_page_3
      bg_color: Black
      widgets:
        - meter:
            align: CENTER
            height: 400
            width: 400
            scales:
              - range_from: 28
                range_to: 31
                angle_range: 240
                rotation: 150
                ticks:
                  width: 2
                  count: 31
                  length: 10
                  color: 0x0000FF
                  major: {stride: 10, width: 3, length: 15, color: 0xFFFFFF}
                indicators:
                  - line: {id: barometer_needle, width: 4, color: 0xFF0000}
        - label: {id: barometer_text, styles: date_style, text: "inHg", align: CENTER, y: 85}
        - label: {styles: date_style, text: "Barometer", align: CENTER, y: 65}

    - id: clock_page
      bg_color: Black
      widgets:
        - meter:
            id: analog_clock
            height: 400
            width: 400
            align: CENTER
            bg_color: White
            border_width: 0
            outline_width: 0
            scales:
              - range_from: 0
                range_to: 60
                angle_range: 360
                rotation: 270
                ticks:
                  width: 4
                  count: 12
                  length: 15
                  color: 0x000000
                indicators:
                  - line: {id: minute_hand, width: 4, color: 0x000000, r_mod: -15}
                  - line: {id: second_hand, width: 2, color: 0xFF0000, r_mod: -5}
              - range_from: 0
                range_to: 720
                angle_range: 360
                rotation: 270
                indicators:
                  - line: {id: hour_hand, width: 6, color: 0x000000, r_mod: -45}
            widgets:
              - label: {id: day_label, styles: date_style, align: CENTER, y: -60}
              - label: {id: date_label, styles: date_style, align: CENTER, y: 60}

    - id: test1_page
      bg_color: Silver
      widgets:
        - label: {id: current_weather_label_dt0, x: 70, y: 20, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label, x: 40, y: 40, height: 170, width: 320, text_font: montserrat_20, text: '...'}
        - label: {id: current_weather_label_dt1, x: 460, y: 20, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label_1, x: 440, y: 40, height: 170, width: 320, text_font: montserrat_20, text: '...'}
        - label: {id: current_weather_label_dt2, x: 70, y: 240, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label_2, x: 40, y: 260, height: 170, width: 320, text_font: montserrat_20, text: '...'}
        - label: {id: current_weather_label_dt3, x: 460, y: 240, text_font: montserrat_20, text: '...'}
        - textarea: {id: current_weather_label_3, x: 440, y: 260, height: 170, width: 320, text_font: montserrat_20, text: '...'}

  top_layer:
    widgets:
      - obj:
          align: bottom_mid
          width: 100%
          height: 40
          bg_color: 0x2F8CD8
          bg_opa: COVER
          border_width: 0
          pad_all: 0
          widgets:
            - buttonmatrix:
                align: CENTER
                width: 100%
                height: 100%
                styles: header_footer
                id: nav_bar
                rows:
                  - buttons:
                    - text: "\uE0F0" # ON
                      on_press: {then: [switch.turn_on: backlight_switch]}
                    - text: "\uE5C4" # Prev
                      on_press: {then: [lvgl.page.previous: ]}
                    - text: "\uE88A" # Home
                      on_press: {then: [lvgl.page.show: main_page]}
                    - text: "\uE8AC" # OFF
                      on_press: {then: [switch.turn_off: backlight_switch]}
                    - text: "\uE5C8" # Next
                      on_press: {then: [lvgl.page.next: ]}
