esphome:
  name: wavesharetouch1
  friendly_name: wavesharetouch1
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32s3box
  framework:
    type: esp-idf
    version: 5.2.2
    platform_version: 6.7.0
    

# Enable Home Assistant API
api:
  encryption:
    key: "GhDzPzQcLq3xg9LVDrpIolcR5wu5hg/cDJs7wk1vjqM="
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus

ota:
  - platform: esphome
    password: "cf6d2dd8038bcfc63c9f7c98c15adf17"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - component.update: my_online_image
    - lvgl.label.update:
        id: lbl_id
        text:
          format: "%.0fdBm"
          args: [ 'id(wifi_sig).get_state()' ]
            
    # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wavesharetouch1 Fallback Hotspot"
    password: "DC8eh1CHRnvt"

packages:
  common_files:
    url: https://github.com/agillis/esphome-configs
    ref: main # optional
    files: [modules/common/color.yaml,
            modules/common/fonts.yaml]

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG

i2c:
  sda: GPIO08
  scl: GPIO09
  scan: True
  id: bus_a

external_components:

  # CH422G I/O Expander
  # https://github.com/esphome/esphome/pull/7356
  - source: github://pr#7356
    components: [ch422g]

ch422g:
  - id: io_ex
    address: 0x24

# Toggles backlight of Waveshare ESP32-S3-Touch-LCD-4.3
switch:
  - platform: gpio
    name: "Backlight Toggle"
    pin:
      ch422g: io_ex
      number: 2
        #      allow_other_uses: true
# CH422G saves the last state internally, but gpio switch sets state as off except when using RESTORE_ modes
    restore_mode: ALWAYS_ON


time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago
    on_time_sync:
#      - script.execute: time_update
      - if:
          condition:
            lambda: 'return id(device_last_restart).state == "";'
          then:
            - text_sensor.template.publish:
                id: device_last_restart
                state: !lambda 'return id(homeassistant_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'

    on_time:
      - minutes: "*"
        then:
          - script.execute: wifisig_update



script:
  - id: wifisig_update
    then:
      - lvgl.label.update:
          id: lbl_id 
          text:
            format: "%.0fdBm"
            args: [ 'id(wifi_sig).get_state()' ]            
  

display:
  - platform: rpi_dpi_rgb
    id: my_display
    auto_clear_enabled: false
    update_interval: never
    color_order: RGB
    pclk_frequency: 14MHz
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: false
    hsync_back_porch: 10 #30
    hsync_front_porch: 20 #210 
    hsync_pulse_width: 10 #30
    vsync_back_porch: 10 #4
    vsync_front_porch: 10 #4
    vsync_pulse_width: 10 #4
    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7

touchscreen:
  platform: gt911
  id: my_touchscreen
  interrupt_pin: GPIO4
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );
http_request:
  verify_ssl: False

online_image:
  #  - url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/280px-PNG_transparency_demonstration_1.png"
  #- url: "http://homeassistant.local:8123/local/test1.png"
  - url: "http://homeassistant.local:8123/local/Paris800_480.png"
    format: png
    id: my_online_image
    type: RGB565
    resize: 800x480
    on_download_finished:
      #  component.update: my_display
      lvgl.image.update:
        id: first_image
        src: my_online_image
      

image:
  - file: wxmedium.png
    id: Paris_image
    resize: 750x420
    type: RGB565

lvgl:
  buffer_size: 25%
  pages:
    - id: main_page
      bg_color: 0x022000
      widgets:
          - image:
              src: Paris_image
              align: CENTER
              id: first_image

    - id: page_2
      widgets:
        - label:
            align: CENTER
            id: lbl_id
            text_font: montserrat_28
            recolor: true
            text: "#FF0000 write# #00FF00 colored# #0000FF text#"
  
        - label:
            align: TOP_MID
            id: lbl_symbol
            text_font: montserrat_28
            text: "\uF013"
         
    - id: page_3
      widgets:
        -  obj:
            x: 10
            y: 10
            width: 220
            height: 300
            bg_color: green
          
  top_layer:
    widgets:
      - buttonmatrix:
          align: bottom_mid
          styles: header_footer
          pad_all: 0
          outline_width: 0
          id: top_layer
          items:
            styles: header_footer
          rows:
            - buttons:
              - id: page_prev
                text: "\uF053"
                on_press:
                  then:
                    lvgl.page.previous:
              - id: page_home
                text: "\uF015"
                on_press:
                  then:
                    lvgl.page.show: main_page
              - id: page_next
                text: "\uF054"
                on_press:
                  then:
                    lvgl.page.next:
      - label:
          text: "\uF1EB"
          id: lbl_hastatus
          hidden: true
          align: top_right
          x: -2
          y: 7
          text_align: right
          text_color: 0xFFFFFF                      

  theme:
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 1
      text_color: 0xFFFFFF
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked: # set some button colors to be different in checked state
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
    buttonmatrix:
      bg_opa: TRANSP
      border_color: 0x0077b3
      border_width: 0
      text_color: 0xFFFFFF
      pad_all: 0
      items: # set all your buttonmatrix buttons to use your custom defined styles and font
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        pressed:
          bg_color: 0x006699
          bg_grad_color: 0x00334d
        checked:
          bg_color: 0x1d5f96
          bg_grad_color: 0x03324A
          text_color: 0x005580
    switch:
      bg_color: 0xC0C0C0
      bg_grad_color: 0xb0b0b0
      bg_grad_dir: VER
      bg_opa: COVER
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_grad_color: 0xC0C0C0
        bg_grad_dir: VER
        bg_opa: COVER
    slider:
      border_width: 1
      border_opa: 15%
      bg_color: 0xcccaca
      bg_opa: 15%
      indicator:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
  style_definitions:
        - id: header_footer
          bg_color: 0x2F8CD8
          bg_grad_color: 0x005782
          bg_grad_dir: VER
          bg_opa: COVER
          border_opa: TRANSP
          radius: 0
          pad_all: 0
          pad_row: 0
          pad_column: 0
          border_color: 0x0077b3
          text_color: 0xFFFFFF
          width: 100%
          height: 30
        - id: date_style      # choose an ID for your definition
          text_font: unscii_16
          align: center
          text_color: 0x000000
          bg_opa: cover
          radius: 4
          pad_all: 2


text_sensor:
  - platform: version
    id: esphome_version
    name: "ESPHome Version"

  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic

  - platform: homeassistant
    id: weatherforecastd1
    entity_id: sensor.weather_forecast_d1

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: "Waveshare1 Touch WiFi Signal Sensor"
    id: wifi_sig
    update_interval: 60s
 
  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.first_air_quality_monitor_temperature

  - platform: homeassistant
    id: inside_humidity
    entity_id: sensor.first_air_quality_monitor_humidity

  - platform: homeassistant
    id: barometer_pressure
    entity_id: sensor.devtest2_bme280_pressure_devtest2

  - platform: homeassistant 
    id: barometer_pressure_online
    entity_id: sensor.pressurecurrent

  - platform: homeassistant
    id: dewpoint
    entity_id: sensor.dewpointcurrent

  - platform: homeassistant
    id: cloudcover
    entity_id: sensor.cloudcovercurrent

  - platform: homeassistant
    id: tempforecastd1 
    entity_id: sensor.temperature_forecast_d1

  - platform: uptime
    type: seconds
    name: Uptime Sensor
 
# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"

web_server:
  port: 80
  include_internal: True
  version: 3
    

captive_portal:
    
