#backlight etc insights from https://github.com/iamfaraz/Waveshare_ST7262_ESPHome_LVGL/blob/main/hadisplay.yaml#L92
esphome:
  name: waveshare7inch
  friendly_name: waveshare7inch
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288
    board_build.flash_size: 8MB


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    platform_version: 6.8.1
    version: 5.3.0
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

  

# Enable logging
logger:
  level: DEBUG
  hardware_uart: UART0

# Enable Home Assistant API
api:
  encryption:
    key: "Dgnfz00FQ13sV8dbeFs2Qq8GKbnaKLQLYAJyYlgqDGw="

ota:
  - platform: esphome
    password: "47cd6b83e7204067ea2e46f0fced55da"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waveshare7Inch Fallback Hotspot"
    password: "C39c7PHHW3m1"

packages:
  common_files:
    url: https://github.com/agillis/esphome-configs
    ref: main # optional
    files: [modules/common/color.yaml,
            modules/common/fonts.yaml]

external_components:
#  - source: github://pr#7427
#    components: [lvgl, font]
#
#  # CH422G I/O Expander
#  # https://github.com/esphome/esphome/pull/7356
#  - source: github://pr#7356
#    components: [ch422g]
#
#  # rpi_dpi_rgb
#  # https://github.com/esphome/esphome/pull/7383
#  - source: github://pr#7383
#    components: [rpi_dpi_rgb]


i2c:
  - id: bus_a
    sda: GPIO8
    scl: GPIO9
    scan: true

#ch422g:
#  - id: io_ex
#    address: 0x24
#
## Toggles backlight of Waveshare ESP32-S3-Touch-LCD-4.3
#switch:
#  - platform: gpio
#    name: "Backlight Toggle"
#    pin: 
#      ch422g: io_ex
#      number: 2
#      allow_other_uses: true
## CH422G saves the last state internally, but gpio switch sets state as off except when using RESTORE_ modes
#    restore_mode: ALWAYS_ON

touchscreen:
  platform: gt911
  address: 0x5D
  id: my_touchscreen
  update_interval: 16ms
  interrupt_pin: 4
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );

display:
  - platform: rpi_dpi_rgb
    id: my_display
    #rotation: 90
    auto_clear_enabled: false
    update_interval: never
    color_order: RGB
    pclk_frequency: 14MHz
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
#    reset_pin:
#      ch422g: io_ex
#      number: 3
#    enable_pin:
#      ch422g: io_ex
#      number: 2
#      allow_other_uses: true
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: false
    hsync_back_porch: 10
    hsync_front_porch: 20
    hsync_pulse_width: 10
    vsync_back_porch: 10
    vsync_front_porch: 10
    vsync_pulse_width: 10
    data_pins:
      red:
        - 1 # R3
        - 2 # R4
        - 42 # R5
        - 41 # R6
        - 40 # R7
      green:
        - 39 # G2
        - 0 # G3
        - 45 # G4
        - 48 # G5
        - 47 # G6
        - 21 # G7
      blue:
        - 14 # B3
        - 38 # B4
        - 18 # B5
        - 17 # B6
        - 10 # B7

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago
    on_time_sync:
      - script.execute: time_update
      - if:
          condition:
            lambda: 'return id(device_last_restart).state == "";'
          then:
            - text_sensor.template.publish:
                id: device_last_restart
                state: !lambda 'return id(homeassistant_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
#below modified from https://esphome.io/cookbook/lvgl#an-analog-clock with addition of second hand
    on_time:
      - seconds: "*"
        then:
          - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.indicator.update:
          id: second_hand
          value: !lambda |-
            return id(homeassistant_time).now().second;
      - lvgl.indicator.update:
          id: minute_hand
          value: !lambda |-
            return id(homeassistant_time).now().minute;
      - lvgl.indicator.update:
          id: hour_hand
          value: !lambda |-
            auto now = id(homeassistant_time).now();
            return std::fmod(now.hour, 12) * 60 + now.minute;

lvgl:
  buffer_size: 25%
  pages:
    - id: main_page
      widgets:
        - label:
            align: CENTER
            y: 20
            text_font: montserrat_44
            text: 'Lance Rules! Yes he does...'
        - obj:
            align: TOP_MID
            styles: header_footer
            widgets:
              - label:
                  text: "ESPHome LVGL Display"
                  align: CENTER
                  text_align: CENTER
                  text_color: 0xFFFFFF


    - id: meter_page_1
      widgets:
          - meter:
              align: LEFT_MID
              height: 350
              width: 350
              scales:
                - range_from: 00 # scale for the needle value
                  range_to: 1000
                  angle_range: 240
                  rotation: 150
                  indicators:
                    - line:
                        id: temperature_needle
                        width: 2
                        color: 0xFF0000
                        r_mod: -4
                    - tick_style:
                        start_value: 0
                        end_value: 100
                        color_start: 0x0000bd
                        color_end: 0xbd0000
                        width: 1
                - range_from: 0 # scale for the value labels
                  range_to: 100
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 1
                    count: 51
                    length: 10
                    color: 0x000000
                    major:
                      stride: 5
                      width: 2
                      length: 10
                      color: 0x404040
                      label_gap: 10
              widgets:
                - label:
                    id: temperature_text
                    text: "-.- F"
                    align: CENTER
                    y: 45
                - label:
                    text: "Inside Temp"
                    align: CENTER
                    y: 65


          - meter:
              align: RIGHT_MID
              height: 350
              width: 350
              scales:
                - range_from: 00 # scale for the needle value
                  range_to: 1000
                  angle_range: 240
                  rotation: 150
                  indicators:
                    - line:
                        id: humidity_needle
                        width: 2
                        color: 0xFF0000
                        r_mod: -4
                    - tick_style:
                        start_value: 0
                        end_value: 100
                        color_start: 0x0000bd
                        color_end: 0xbd0000
                        width: 1
                - range_from: 0 # scale for the value labels
                  range_to: 100
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 1
                    count: 51
                    length: 10
                    color: 0x000000
                    major:
                      stride: 5
                      width: 2
                      length: 10
                      color: 0x404040
                      label_gap: 10
              widgets:
                - label:
                    id: humidity_text
                    text: "-.- %"
                    align: CENTER
                    y: 45
                - label:
                    text: "Inside Humidity"
                    align: CENTER
                    y: 65
    - id: meter_page_2
      widgets:
          - meter:
              align: LEFT_MID
              height: 350
              width: 350
              scales:
                - range_from: 00 # scale for the needle value
                  range_to: 1000
                  angle_range: 240
                  rotation: 150
                  indicators:
                    - line:
                        id: temperature_needle_2
                        width: 2
                        color: 0xFF0000
                        r_mod: -4
                    - tick_style:
                        start_value: 0
                        end_value: 100
                        color_start: 0x0000bd
                        color_end: 0xbd0000
                        width: 1
                - range_from: 0 # scale for the value labels
                  range_to: 100
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 1
                    count: 51
                    length: 10
                    color: 0x000000
                    major:
                      stride: 5
                      width: 2
                      length: 10
                      color: 0x404040
                      label_gap: 10
              widgets:
                - label:
                    id: temperature_text_2
                    text: "-.- F"
                    align: CENTER
                    y: 45
                - label:
                    text: "Outside Temp"
                    align: CENTER
                    y: 65


          - meter:
              align: RIGHT_MID
              height: 350
              width: 350
              scales:
                - range_from: 00 # scale for the needle value
                  range_to: 1000
                  angle_range: 240
                  rotation: 150
                  indicators:
                    - line:
                        id: humidity_needle_2
                        width: 2
                        color: 0xFF0000
                        r_mod: -4
                    - tick_style:
                        start_value: 0
                        end_value: 100
                        color_start: 0x0000bd
                        color_end: 0xbd0000
                        width: 1
                - range_from: 0 # scale for the value labels
                  range_to: 100
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 1
                    count: 51
                    length: 10
                    color: 0x000000
                    major:
                      stride: 5
                      width: 2
                      length: 10
                      color: 0x404040
                      label_gap: 10
              widgets:
                - label:
                    id: humidity_text_2
                    text: "-.- %"
                    align: CENTER
                    y: 45
                - label:
                    text: "Outside Humidity"
                    align: CENTER
                    y: 65


    - id: clock_page
      width: 100%
      bg_color: Black
      widgets:
          # Outer Clock Container
          - obj:
              height: 470
              width: 470
              align: center
              pad_all: 4
              bg_color: Black
              border_width: 0
              widgets:
              - meter:
                  height: 100%
                  width: 100%
                  align: center
                  bg_color: White

                  scales:
                    # Minor ticks
                    - ticks:
                        width: 2
                        count: 61
                        length: 10
                        color: Black
                      range_from: 0
                      range_to: 60
                      angle_range: 360
                      rotation: 270

                      # Minuite hand
                      indicators:
                        - line:
                            id: minute_hand
                            width: 3
                            color: Black
                            r_mod: -1
                    # Major ticks
                    - angle_range: 330
                      rotation: 300
                      range_from: 1
                      range_to: 12
                      ticks:
                        width: 3
                        count: 12
                        length: 20
                        color: Black

                    # Hour hand
                    - angle_range: 360
                      rotation: 270
                      range_from: 0
                      range_to: 720
                      indicators:
                        - line:
                            id: hour_hand
                            width: 4
                            color: Black
                            r_mod: -40

                    # Second hand
                    - angle_range: 360
                      rotation: 270
                      range_from: 0
                      range_to: 60
                      indicators:
                        - line:
                            id: second_hand
                            width: 2
                            color: Red
                            r_mod: -10


  top_layer:
    widgets:
      - buttonmatrix:
          align: bottom_mid
          styles: header_footer
          pad_all: 0
          outline_width: 0
          id: top_layer
          items:
            styles: header_footer
          rows:
            - buttons:
              - id: page_prev
                text: "\uF053"
                on_press:
                  then:
                    lvgl.page.previous:
              - id: page_home
                text: "\uF015"
                on_press:
                  then:
                    lvgl.page.show: main_page
              - id: page_next
                text: "\uF054"
                on_press:
                  then:
                    lvgl.page.next:


  theme:
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 1
      text_color: 0xFFFFFF
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked: # set some button colors to be different in checked state
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
    buttonmatrix:
      bg_opa: TRANSP
      border_color: 0x0077b3
      border_width: 0
      text_color: 0xFFFFFF
      pad_all: 0
      items: # set all your buttonmatrix buttons to use your custom defined styles and font
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        pressed:
          bg_color: 0x006699
          bg_grad_color: 0x00334d
        checked:
          bg_color: 0x1d5f96
          bg_grad_color: 0x03324A
          text_color: 0x005580
    switch:
      bg_color: 0xC0C0C0
      bg_grad_color: 0xb0b0b0
      bg_grad_dir: VER
      bg_opa: COVER
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_grad_color: 0xC0C0C0
        bg_grad_dir: VER
        bg_opa: COVER
    slider:
      border_width: 1
      border_opa: 15%
      bg_color: 0xcccaca
      bg_opa: 15%
      indicator:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
  style_definitions:
    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 100%
      height: 30

sensor:
  - platform: wifi_signal
    name: "Waveshare 7 Inch Signal Sensor"
    update_interval: 60s

  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.devtest2_bme280_temperature_devtest2
    on_value:
      - lvgl.indicator.update:
          id: temperature_needle
          value: !lambda return x * 10;
      - lvgl.label.update:
          id: temperature_text
          text:
            format: "%.1f°F"
            args: [ 'x' ]

  - platform: homeassistant  
    id: inside_humidity
    entity_id: sensor.devtest2_bme280_humidity_devtest2
    on_value:
      - lvgl.indicator.update:
          id: humidity_needle
          value: !lambda return x * 10;
      - lvgl.label.update:
          id: humidity_text
          text:
            format: "%.1f%%"
            args: [ 'x' ]

  - platform: homeassistant
    id: outside_temperature
    entity_id: sensor.tempcurrent
    on_value:
      - lvgl.indicator.update:
          id: temperature_needle_2
          value: !lambda return x * 10;
      - lvgl.label.update:
          id: temperature_text_2
          text:
            format: "%.1f°F"
            args: [ 'x' ]

  - platform: homeassistant
    id: outside_humidity
    entity_id: sensor.humiditycurrent
    on_value:
      - lvgl.indicator.update:
          id: humidity_needle_2
          value: !lambda return x * 10;
      - lvgl.label.update:
          id: humidity_text_2
          text:
            format: "%.1f%%"
            args: [ 'x' ]

  - platform: homeassistant
    id: barometer_pressure
    entity_id: sensor.pressurecurrent

  - platform: homeassistant
    id: dewpoint
    entity_id: sensor.dewpointcurrent

  - platform: homeassistant
    id: cloudcover
    entity_id: sensor.cloudcovercurrent

  - platform: homeassistant
    id: weatherforecastd1
    entity_id: sensor.weather_forecast_d1

  - platform: homeassistant
    id: tempforecastd1
    entity_id: sensor.temperature_forecast_d1
      
  - platform: uptime
    type: seconds
    name: Uptime Sensor

text_sensor:
  - platform: version
    name: "ESPHome Version" 
  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic
 
# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"  

web_server:
  port: 80
  include_internal: True
  version: 3

captive_portal:
    
