esphome:
  name: waveshare7inch
  friendly_name: waveshare7inch

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
  

# Enable logging
logger:
  level: DEBUG
  hardware_uart: UART0

# Enable Home Assistant API
api:
  encryption:
    key: "Dgnfz00FQ13sV8dbeFs2Qq8GKbnaKLQLYAJyYlgqDGw="

ota:
  - platform: esphome
    password: "47cd6b83e7204067ea2e46f0fced55da"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waveshare7Inch Fallback Hotspot"
    password: "C39c7PHHW3m1"

sensor:
  - platform: wifi_signal
    name: "Waveshare 7 Inch Signal Sensor"
    update_interval: 60s

  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.devtest2_bme280_temperature_devtest2

  - platform: homeassistant  
    id: inside_humidity
    entity_id: sensor.devtest2_bme280_humidity_devtest2
  
  - platform: uptime
    type: seconds
    name: Uptime Sensor

text_sensor:
  - platform: version
    name: "ESPHome Version" 

 
# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"  

web_server:
  port: 80
  include_internal: True




captive_portal:
    